/** Account-experience UI strings for the trilingual layer, part L.
 * Generated to close the coverage gap on the surfaces a Chinese-locale account
 * traverses: account creation, onboarding, agent / super-agent / sub-agent
 * dashboards, account / wallet / settings, checkout, and the storefront chrome.
 * Merged by lib/i18n/ui-dict.ts (CURATED still wins on overlap). Keys are the
 * EXACT decoded runtime strings; '#' is the number wildcard.
 */

export const EXTRACTED_L: Record<string, { 'zh-CN': string; 'zh-TW': string }> = {
  // ── Account creation / sign-up / sign-in ─────────────────
  "Create Free Account": { 'zh-CN': "创建免费账户", 'zh-TW': "建立免費帳戶" },
  "Create a free account to save compounds, build reading queues, subscribe to research updates, and browse your agent's storefront with wholesale pricing.": { 'zh-CN': "创建免费账户以收藏化合物、建立阅读清单、订阅研究更新，并以批发价浏览您代理的店铺。", 'zh-TW': "建立免費帳戶以收藏化合物、建立閱讀清單、訂閱研究更新，並以批發價瀏覽您代理的店鋪。" },
  "Already Have An Account?": { 'zh-CN': "已有账户？", 'zh-TW': "已有帳戶？" },
  "Already Have An Account? Sign In": { 'zh-CN': "已有账户？登录", 'zh-TW': "已有帳戶？登入" },
  "Or Sign Up With A Username": { 'zh-CN': "或使用用户名注册", 'zh-TW': "或使用使用者名稱註冊" },
  "Choose A Username": { 'zh-CN': "选择用户名", 'zh-TW': "選擇使用者名稱" },
  "Choose A New Password": { 'zh-CN': "设置新密码", 'zh-TW': "設定新密碼" },
  "First And Last Name": { 'zh-CN': "名字和姓氏", 'zh-TW': "名字和姓氏" },
  "Full Name (Optional)": { 'zh-CN': "全名（可选）", 'zh-TW': "全名（選填）" },
  "Email (Optional)": { 'zh-CN': "电子邮箱（可选）", 'zh-TW': "電子郵件（選填）" },
  "Phone (Optional)": { 'zh-CN': "电话（可选）", 'zh-TW': "電話（選填）" },
  "Phone Number (Optional)": { 'zh-CN': "电话号码（可选）", 'zh-TW': "電話號碼（選填）" },
  "Enter Your Email": { 'zh-CN': "输入您的电子邮箱", 'zh-TW': "輸入您的電子郵件" },
  "Enter Your Real Email Address": { 'zh-CN': "输入您的真实电子邮箱地址", 'zh-TW': "輸入您的真實電子郵件地址" },
  "Your Real Email": { 'zh-CN': "您的真实邮箱", 'zh-TW': "您的真實電子郵件" },
  "Use A Different Email": { 'zh-CN': "使用其他邮箱", 'zh-TW': "使用其他電子郵件" },
  "Who Referred You?": { 'zh-CN': "谁推荐了您？", 'zh-TW': "誰推薦了您？" },
  "Agent Or Researcher Username / Code": { 'zh-CN': "代理或研究员用户名／代码", 'zh-TW': "代理或研究員使用者名稱／代碼" },
  "Enter the username of the agent or researcher who referred you, or their referral code.": { 'zh-CN': "输入推荐您的代理或研究员的用户名，或其推荐代码。", 'zh-TW': "輸入推薦您的代理或研究員的使用者名稱，或其推薦代碼。" },
  "Enter your agent's username to get linked to their store.": { 'zh-CN': "输入您代理的用户名以关联到其店铺。", 'zh-TW': "輸入您代理的使用者名稱以關聯到其店鋪。" },
  "Referral Code (Optional)": { 'zh-CN': "推荐代码（可选）", 'zh-TW': "推薦代碼（選填）" },
  "Sign-Up Promo Code": { 'zh-CN': "注册优惠码", 'zh-TW': "註冊優惠碼" },
  "Promo Code (Optional)": { 'zh-CN': "优惠码（可选）", 'zh-TW': "優惠碼（選填）" },
  "Have a promo code? Enter it to unlock your sign-up reward.": { 'zh-CN': "有优惠码吗？输入即可解锁您的注册奖励。", 'zh-TW': "有優惠碼嗎？輸入即可解鎖您的註冊獎勵。" },
  "Not sure? Leave it blank and tap Skip. You can update this later from your account settings.": { 'zh-CN': "不确定？留空并点击“跳过”。您稍后可在账户设置中更新。", 'zh-TW': "不確定？留空並點擊「略過」。您稍後可在帳戶設定中更新。" },
  "This is optional. You can skip it.": { 'zh-CN': "此项为可选。您可以跳过。", 'zh-TW': "此項為選填。您可以略過。" },
  "All Fields Are Required Unless Marked Optional.": { 'zh-CN': "除标注为可选外，所有字段均为必填。", 'zh-TW': "除標註為選填外，所有欄位均為必填。" },
  "Join Pep Nation Lab For Peptide Education And Research": { 'zh-CN': "加入 Pep Nation Lab，进行肽类教育与研究", 'zh-TW': "加入 Pep Nation Lab，進行肽類教育與研究" },
  "Become A Peptide Distribution Agent": { 'zh-CN': "成为肽类分销代理", 'zh-TW': "成為肽類分銷代理" },

  // ── Password / reset / 2FA ───────────────────────────────
  "Password *": { 'zh-CN': "密码 *", 'zh-TW': "密碼 *" },
  "Password Reset": { 'zh-CN': "重置密码", 'zh-TW': "重設密碼" },
  "Password Updated": { 'zh-CN': "密码已更新", 'zh-TW': "密碼已更新" },
  "Reset Your Password": { 'zh-CN': "重置您的密码", 'zh-TW': "重設您的密碼" },
  "Reset Code": { 'zh-CN': "重置代码", 'zh-TW': "重設代碼" },
  "Send Reset Code": { 'zh-CN': "发送重置代码", 'zh-TW': "傳送重設代碼" },
  "Enter Your New Password Below.": { 'zh-CN': "在下方输入您的新密码。", 'zh-TW': "在下方輸入您的新密碼。" },
  "Enter The Email Address On Your Account To Receive A #-Digit Reset Code.": { 'zh-CN': "输入您账户上的电子邮箱以接收 # 位重置代码。", 'zh-TW': "輸入您帳戶上的電子郵件以接收 # 位重設代碼。" },
  ", A #-Digit Code Was Sent. Enter It Below With Your New Password.": { 'zh-CN': "，已发送 # 位代码。请在下方连同新密码一并输入。", 'zh-TW': "，已傳送 # 位代碼。請在下方連同新密碼一併輸入。" },
  ". New Passwords Must Be At Least # Characters.": { 'zh-CN': "。新密码至少需 # 个字符。", 'zh-TW': "。新密碼至少需 # 個字元。" },
  "Your Password Has Been Reset. You Can Now Sign In With Your New Password.": { 'zh-CN': "您的密码已重置。您现在可以使用新密码登录。", 'zh-TW': "您的密碼已重設。您現在可以使用新密碼登入。" },
  "Return To Sign In": { 'zh-CN': "返回登录", 'zh-TW': "返回登入" },
  "Resetting...": { 'zh-CN': "正在重置…", 'zh-TW': "正在重設…" },
  "If An Account Exists For": { 'zh-CN': "如果存在对应账户", 'zh-TW': "如果存在對應帳戶" },
  "Two-Factor Authentication Is Enabled On This Account.": { 'zh-CN': "此账户已启用双重验证。", 'zh-TW': "此帳戶已啟用雙重驗證。" },
  "Two-Factor QR Code": { 'zh-CN': "双重验证二维码", 'zh-TW': "雙重驗證 QR 碼" },
  "Add A Second Factor With An Authenticator App Like Google Authenticator, Authy, Or #Password.": { 'zh-CN': "使用 Google Authenticator、Authy 或 #Password 等验证器应用添加第二重验证。", 'zh-TW': "使用 Google Authenticator、Authy 或 #Password 等驗證器應用程式新增第二重驗證。" },
  "The Following Factor Is Active On This Account.": { 'zh-CN': "此账户已启用以下验证方式。", 'zh-TW': "此帳戶已啟用以下驗證方式。" },
  "Code From App": { 'zh-CN': "来自应用的代码", 'zh-TW': "來自應用程式的代碼" },
  "Or Paste This Secret Manually": { 'zh-CN': "或手动粘贴此密钥", 'zh-TW': "或手動貼上此密鑰" },
  "Save Your Backup Secret In A Safe Place. If You Lose Your Phone, This Is The Only Way Back In.": { 'zh-CN': "请将备份密钥保存在安全的地方。如果您丢失手机，这是重新登录的唯一方式。", 'zh-TW': "請將備份密鑰儲存在安全的地方。如果您遺失手機，這是重新登入的唯一方式。" },
  "Step #: Scan This QR Code With Your Authenticator App.": { 'zh-CN': "第 # 步：使用您的验证器应用扫描此二维码。", 'zh-TW': "第 # 步：使用您的驗證器應用程式掃描此 QR 碼。" },
  "Step #: Enter The #-Digit Code From Your App": { 'zh-CN': "第 # 步：输入应用中的 # 位代码", 'zh-TW': "第 # 步：輸入應用程式中的 # 位代碼" },
  "#-Digit Verification Code": { 'zh-CN': "# 位验证码", 'zh-TW': "# 位驗證碼" },
  "Must Match": { 'zh-CN': "必须匹配", 'zh-TW': "必須相符" },
  "Min # chars": { 'zh-CN': "至少 # 个字符", 'zh-TW': "至少 # 個字元" },

  // ── Onboarding wizard ────────────────────────────────────
  "Setup": { 'zh-CN': "设置", 'zh-TW': "設定" },
  "Pep Nation": { 'zh-CN': "Pep Nation", 'zh-TW': "Pep Nation" },
  "% Complete": { 'zh-CN': "% 完成", 'zh-TW': "% 完成" },
  "% Done. Let Us Pick Up Where You Left Off.": { 'zh-CN': "% 完成。让我们从您上次离开的地方继续。", 'zh-TW': "% 完成。讓我們從您上次離開的地方繼續。" },
  "Secure Your Password": { 'zh-CN': "设置您的密码", 'zh-TW': "設定您的密碼" },
  "Your Account Was Created With A Temporary Password. Choose Your Own Private Password To Continue.": { 'zh-CN': "您的账户是使用临时密码创建的。请设置您自己的私人密码以继续。", 'zh-TW': "您的帳戶是使用臨時密碼建立的。請設定您自己的私人密碼以繼續。" },
  "Set Password And Continue": { 'zh-CN': "设置密码并继续", 'zh-TW': "設定密碼並繼續" },
  "Confirm Your Contact Details": { 'zh-CN': "确认您的联系方式", 'zh-TW': "確認您的聯絡方式" },
  "Make Sure Your Name, Phone, And Email Are Correct. We Use These For Order Updates And Account Recovery.": { 'zh-CN': "请确保您的姓名、电话和电子邮箱正确无误。我们用它们发送订单更新和进行账户恢复。", 'zh-TW': "請確保您的姓名、電話和電子郵件正確無誤。我們用它們傳送訂單更新和進行帳戶復原。" },
  "Add Your Warehouse Address": { 'zh-CN': "添加您的仓库地址", 'zh-TW': "新增您的倉庫地址" },
  "This Is Where Your Inventory Shipments Are Delivered. Your Restocks From Pep Nation Ship To This Address, So Make Sure It Is Accurate.": { 'zh-CN': "这是您的库存货件送达的地址。您从 Pep Nation 补货的商品将寄送到此地址，请确保准确无误。", 'zh-TW': "這是您的庫存貨件送達的地址。您從 Pep Nation 補貨的商品將寄送到此地址，請確保準確無誤。" },
  "Suite / Unit (Optional)": { 'zh-CN': "套房／单元（可选）", 'zh-TW': "套房／單元（選填）" },
  "Suite # (Optional)": { 'zh-CN': "# 号套房（可选）", 'zh-TW': "# 號套房（選填）" },
  "Suite Or Apartment": { 'zh-CN': "套房或公寓", 'zh-TW': "套房或公寓" },
  "We Found A Standardized Address": { 'zh-CN': "我们找到一个标准化地址", 'zh-TW': "我們找到一個標準化地址" },
  "Use Standardized Address": { 'zh-CN': "使用标准化地址", 'zh-TW': "使用標準化地址" },
  "Use What I Entered": { 'zh-CN': "使用我输入的地址", 'zh-TW': "使用我輸入的地址" },
  "Set Up Your Storefront": { 'zh-CN': "设置您的店铺", 'zh-TW': "設定您的店鋪" },
  "Choose The Web Address Your Researchers Will Use To Reach Your Store. Pick Something Short And Memorable -- This Is Your Public Storefront Link.": { 'zh-CN': "选择您的研究员用来访问您店铺的网址。挑选简短易记的名称——这是您对外公开的店铺链接。", 'zh-TW': "選擇您的研究員用來訪問您店鋪的網址。挑選簡短易記的名稱——這是您對外公開的店鋪連結。" },
  "Storefront Web Address": { 'zh-CN': "店铺网址", 'zh-TW': "店鋪網址" },
  "Checking Availability...": { 'zh-CN': "正在检查可用性…", 'zh-TW': "正在檢查可用性…" },
  "Display Name (Shown On Your Store)": { 'zh-CN': "显示名称（显示在您的店铺上）", 'zh-TW': "顯示名稱（顯示在您的店鋪上）" },
  "Add Your Payment Methods": { 'zh-CN': "添加您的收款方式", 'zh-TW': "新增您的收款方式" },
  "Researchers Pay You Directly Through These Handles At Checkout. Only One Method Is Required To Finish Setup, But Adding More Is Recommended So Every Researcher Can Pay The Way They Prefer.": { 'zh-CN': "研究员在结账时通过这些账号直接向您付款。完成设置只需一种方式，但建议多添加几种，以便每位研究员都能以其偏好的方式付款。", 'zh-TW': "研究員在結帳時透過這些帳號直接向您付款。完成設定只需一種方式，但建議多新增幾種，以便每位研究員都能以其偏好的方式付款。" },
  "How Product Pricing Works": { 'zh-CN': "产品定价的运作方式", 'zh-TW': "產品定價的運作方式" },
  "How Product Pricing And Markup Work": { 'zh-CN': "产品定价与加价的运作方式", 'zh-TW': "產品定價與加價的運作方式" },
  "Every Product Has A Wholesale Cost. You Earn The Difference Between That Cost And The Price You Sell It For.": { 'zh-CN': "每件产品都有批发成本。您赚取该成本与您售价之间的差额。", 'zh-TW': "每件產品都有批發成本。您賺取該成本與您售價之間的差額。" },
  "Every Product Has A Wholesale Cost. Your Markup Is The Percentage Added On Top Of That Cost To Set Your Price. A Higher Markup Means More Margin Per Sale.": { 'zh-CN': "每件产品都有批发成本。加价是在该成本之上加上的百分比，用以设定您的售价。加价越高，每笔销售的利润越高。", 'zh-TW': "每件產品都有批發成本。加價是在該成本之上加上的百分比，用以設定您的售價。加價越高，每筆銷售的利潤越高。" },
  "Save Markup And Continue": { 'zh-CN': "保存加价并继续", 'zh-TW': "儲存加價並繼續" },
  "Your Default Markup % (Recommended: #)": { 'zh-CN': "您的默认加价 %（推荐：#）", 'zh-TW': "您的預設加價 %（建議：#）" },
  "We Have Set Your Default Markup To # To Get You Started. You Can Change This Anytime, And You Can Override The Price On Individual Products From The Products Page.": { 'zh-CN': "我们已将您的默认加价设为 # 以便您快速上手。您可以随时更改，也可在产品页面单独覆盖各产品的价格。", 'zh-TW': "我們已將您的預設加價設為 # 以便您快速上手。您可以隨時更改，也可在產品頁面單獨覆寫各產品的價格。" },
  "Live Pricing Active -- Your Markup Applies Immediately": { 'zh-CN': "实时定价已启用——您的加价立即生效", 'zh-TW': "即時定價已啟用——您的加價立即生效" },
  "Example:": { 'zh-CN': "示例：", 'zh-TW': "範例：" },
  "A Product With A # Wholesale Cost And A": { 'zh-CN': "一件批发成本为 # 的产品，加价", 'zh-TW': "一件批發成本為 # 的產品，加價" },
  "% Markup Is Priced At": { 'zh-CN': "% 的定价为", 'zh-TW': "% 的定價為" },
  "% Markup, Is Priced At": { 'zh-CN': "%，定价为", 'zh-TW': "%，定價為" },
  "Set Your Agent Markup": { 'zh-CN': "设置您的代理加价", 'zh-TW': "設定您的代理加價" },
  "Set Your Sub-Agent Commissions": { 'zh-CN': "设置您的子代理佣金", 'zh-TW': "設定您的子代理佣金" },
  "Decide How Your Agents Are Priced On Top Of Wholesale Cost. Choose A Flat Markup Or The Gamification Scale. This Is Just The Default For New Agents -- You Can Change The Markup For Any Agent At Any Time From Your Agents Page.": { 'zh-CN': "决定您的代理在批发成本之上的定价方式。选择固定加价或阶梯激励机制。这只是新代理的默认设置——您可随时在代理页面更改任何代理的加价。", 'zh-TW': "決定您的代理在批發成本之上的定價方式。選擇固定加價或階梯激勵機制。這只是新代理的預設設定——您可隨時在代理頁面更改任何代理的加價。" },
  "Flat Markup": { 'zh-CN': "固定加价", 'zh-TW': "固定加價" },
  "Flat Markup:": { 'zh-CN': "固定加价：", 'zh-TW': "固定加價：" },
  "Default Agent Markup %": { 'zh-CN': "默认代理加价 %", 'zh-TW': "預設代理加價 %" },
  "Default Sub-Agent Commission %": { 'zh-CN': "默认子代理佣金 %", 'zh-TW': "預設子代理佣金 %" },
  "One Percentage Across The Board. A Product That Costs # Wholesale, With A": { 'zh-CN': "全线统一的一个百分比。一件批发成本为 # 的产品，加价", 'zh-TW': "全線統一的一個百分比。一件批發成本為 # 的產品，加價" },
  "For Your Agents.": { 'zh-CN': "面向您的代理。", 'zh-TW': "面向您的代理。" },
  "No Flat Rate To Set": { 'zh-CN': "无需设置固定费率", 'zh-TW': "無需設定固定費率" },
  "Volume-Based Pricing": { 'zh-CN': "基于销量的定价", 'zh-TW': "基於銷量的定價" },
  "Your Agents Ride The Platform Volume Ladder: Their Cost Markup Automatically Improves As Their Monthly Volume Grows, So Strong Sellers Earn Better Pricing.": { 'zh-CN': "您的代理跟随平台销量阶梯：随着月销量增长，其成本加价自动优化，因此强势卖家可获得更优价格。", 'zh-TW': "您的代理跟隨平台銷量階梯：隨著月銷量增長，其成本加價自動優化，因此強勢賣家可獲得更優價格。" },
  "There Is No Fixed Percentage With The Gamification Scale -- The Ladder Sets Each Agent's Markup By Their Volume.": { 'zh-CN': "阶梯激励机制没有固定百分比——阶梯会根据每位代理的销量设定其加价。", 'zh-TW': "階梯激勵機制沒有固定百分比——階梯會根據每位代理的銷量設定其加價。" },
  "This Is Only The Default For New Agents. You Can Change Any Agent To A Different Markup Or Method At Any Time From Your Agents Page.": { 'zh-CN': "这只是新代理的默认设置。您可随时在代理页面将任何代理更改为不同的加价或方式。", 'zh-TW': "這只是新代理的預設設定。您可隨時在代理頁面將任何代理更改為不同的加價或方式。" },
  "Save Default And Continue": { 'zh-CN': "保存默认设置并继续", 'zh-TW': "儲存預設設定並繼續" },
  "A Share Of Sales, Not A Markup": { 'zh-CN': "销售分成，而非加价", 'zh-TW': "銷售分成，而非加價" },
  "A Sub-Agent's Commission Is A Percentage Of The Sales They Generate -- It Is Paid Out Of Your Margin, It Does Not Raise The Researcher's Price.": { 'zh-CN': "子代理的佣金是其带来销售额的一定百分比——由您的利润中支付，不会提高研究员的价格。", 'zh-TW': "子代理的佣金是其帶來銷售額的一定百分比——由您的利潤中支付，不會提高研究員的價格。" },
  "You Can Set Any Default Between # And # Percent, And Override It Per Sub-Agent From The Sub-Agents Section.": { 'zh-CN': "您可将默认值设为 # 到 # 之间的任意百分比，并可在子代理板块中为各子代理单独覆盖。", 'zh-TW': "您可將預設值設為 # 到 # 之間的任意百分比，並可在子代理版塊中為各子代理單獨覆寫。" },
  "Sub-Agents Sell On Your Storefront And Earn A Commission On Every Sale They Bring In. Set A Default Rate Now -- It Is Applied Automatically To Every New Sub-Agent, And You Can Still Customize Any Individual Sub-Agent Later.": { 'zh-CN': "子代理在您的店铺销售，并从其带来的每笔销售中赚取佣金。现在设置一个默认费率——它会自动应用于每个新子代理，您之后仍可为任一子代理单独定制。", 'zh-TW': "子代理在您的店鋪銷售，並從其帶來的每筆銷售中賺取佣金。現在設定一個預設費率——它會自動套用於每個新子代理，您之後仍可為任一子代理單獨自訂。" },
  "How Ordering And Credit Work": { 'zh-CN': "下单与信用额度的运作方式", 'zh-TW': "下單與信用額度的運作方式" },
  "What To Know": { 'zh-CN': "须知事项", 'zh-TW': "須知事項" },
  "Share Your Storefront Link": { 'zh-CN': "分享您的店铺链接", 'zh-TW': "分享您的店鋪連結" },
  "This Is The Link Your Researchers Use To Shop With You. Share It By Text Or Email, Or Let Them Scan Your QR Code In Person.": { 'zh-CN': "这是您的研究员用来向您购物的链接。可通过短信或电子邮件分享，或让他们当面扫描您的二维码。", 'zh-TW': "這是您的研究員用來向您購物的連結。可透過簡訊或電子郵件分享，或讓他們當面掃描您的 QR 碼。" },
  "Compliance Acknowledgment": { 'zh-CN': "合规确认", 'zh-TW': "合規確認" },
  "Pep Nation Is A Research-Use-Only Platform. Before You Start Selling, Confirm You Understand The Rules Every Agent Must Follow.": { 'zh-CN': "Pep Nation 是一个仅供研究使用的平台。在开始销售之前，请确认您理解每位代理必须遵守的规则。", 'zh-TW': "Pep Nation 是一個僅供研究使用的平台。在開始銷售之前，請確認您理解每位代理必須遵守的規則。" },
  "Every Product Is Sold Strictly For Laboratory Research Use. Nothing On The Platform Is For Human Or Veterinary Consumption, And You Must Never Present It Otherwise.": { 'zh-CN': "所有产品均严格仅供实验室研究使用。平台上的任何产品均不供人类或动物食用，您绝不得作出相反表述。", 'zh-TW': "所有產品均嚴格僅供實驗室研究使用。平台上的任何產品均不供人類或動物食用，您絕不得作出相反表述。" },
  "Disclaimers Stay On": { 'zh-CN': "免责声明须保持开启", 'zh-TW': "免責聲明須保持開啟" },
  "Your Storefront Carries The Platform's Built-In Disclaimer Gates At Entry, Registration, Add-To-Cart, And Checkout. Never Ask For Them To Be Removed Or Weakened.": { 'zh-CN': "您的店铺在进入、注册、加入购物车和结账环节均设有平台内置的免责声明关卡。切勿要求将其移除或削弱。", 'zh-TW': "您的店鋪在進入、註冊、加入購物車和結帳環節均設有平台內建的免責聲明關卡。切勿要求將其移除或削弱。" },
  "No Medical Claims": { 'zh-CN': "不得作医疗宣称", 'zh-TW': "不得作醫療宣稱" },
  "Do Not Make Dosage, Treatment, Or Health-Benefit Claims When Promoting Your Storefront. Share The Link And Let Researchers Review The Published Research Themselves.": { 'zh-CN': "在推广您的店铺时，不得作出剂量、治疗或健康益处方面的宣称。分享链接，让研究员自行查阅已发表的研究。", 'zh-TW': "在推廣您的店鋪時，不得作出劑量、治療或健康益處方面的宣稱。分享連結，讓研究員自行查閱已發表的研究。" },
  "I Understand And Agree: All Products Are Sold For Laboratory Research Use Only, Are Not For Human Consumption, And I Will Represent Them Accordingly In All Of My Selling And Marketing.": { 'zh-CN': "我理解并同意：所有产品均仅供实验室研究使用，不供人类食用，我将在所有销售和营销中据此进行表述。", 'zh-TW': "我理解並同意：所有產品均僅供實驗室研究使用，不供人類食用，我將在所有銷售和行銷中據此進行表述。" },
  "Agree And Continue": { 'zh-CN': "同意并继续", 'zh-TW': "同意並繼續" },
  "Got It, Continue": { 'zh-CN': "明白了，继续", 'zh-TW': "明白了，繼續" },
  "Save And Continue": { 'zh-CN': "保存并继续", 'zh-TW': "儲存並繼續" },
  "Enter My Dashboard": { 'zh-CN': "进入我的控制台", 'zh-TW': "進入我的控制台" },
  "Congratulations, You Are Now A Pep Nation": { 'zh-CN': "恭喜，您现在是 Pep Nation", 'zh-TW': "恭喜，您現在是 Pep Nation" },
  "What's Next": { 'zh-CN': "接下来", 'zh-TW': "接下來" },
  "Jump Right To It": { 'zh-CN': "立即开始", 'zh-TW': "立即開始" },
  "Understand How You Earn": { 'zh-CN': "了解您如何赚取收益", 'zh-TW': "了解您如何賺取收益" },
  "Your Commission Rate": { 'zh-CN': "您的佣金费率", 'zh-TW': "您的佣金費率" },
  "This Is A Percentage Of The Sales You Generate -- Not A Markup. Track Your Pending And Settled Commission Anytime From Your Dashboard.": { 'zh-CN': "这是您带来销售额的一定百分比——而非加价。您可随时在控制台追踪待结算和已结算的佣金。", 'zh-TW': "這是您帶來銷售額的一定百分比——而非加價。您可隨時在控制台追蹤待結算和已結算的佣金。" },
  "Taking You To Your Dashboard...": { 'zh-CN': "正在带您前往控制台…", 'zh-TW': "正在帶您前往控制台…" },
  "Let Us Guide You": { 'zh-CN': "让我们引导您", 'zh-TW': "讓我們引導您" },

  // ── Notifications step ───────────────────────────────────
  "Notifications Let You Know The Moment You Get A New Order Or Payment. Follow The Steps For Your Device Below. This Step Finishes Only Once Notifications Are Actually On.": { 'zh-CN': "通知会在您收到新订单或付款时第一时间提醒您。请按下方适用于您设备的步骤操作。只有在通知真正开启后，此步骤才算完成。", 'zh-TW': "通知會在您收到新訂單或付款時第一時間提醒您。請按下方適用於您裝置的步驟操作。只有在通知真正開啟後，此步驟才算完成。" },
  "The Most Important Part: When Your Device Asks For Permission, You Must Choose": { 'zh-CN': "最重要的一点：当您的设备请求权限时，您必须选择", 'zh-TW': "最重要的一點：當您的裝置請求權限時，您必須選擇" },
  ". If You Pick Block Or Don't Allow, Notifications Stay Off.": { 'zh-CN': "。如果您选择“阻止”或“不允许”，通知将保持关闭。", 'zh-TW': "。如果您選擇「封鎖」或「不允許」，通知將保持關閉。" },
  "Allow": { 'zh-CN': "允许", 'zh-TW': "允許" },
  "Already Turned Them On? Re-Check": { 'zh-CN': "已经开启了？重新检查", 'zh-TW': "已經開啟了？重新檢查" },
  "Notifications Are Blocked -- How To Unblock": { 'zh-CN': "通知已被阻止——如何解除", 'zh-TW': "通知已被封鎖——如何解除" },
  "Try Again. Turn On Notifications": { 'zh-CN': "重试。开启通知", 'zh-TW': "重試。開啟通知" },
  "I Unblocked It In Settings — Re-Check": { 'zh-CN': "我已在设置中解除阻止 — 重新检查", 'zh-TW': "我已在設定中解除封鎖 — 重新檢查" },
  "Skip For Now — I'll Enable Notifications Later": { 'zh-CN': "暂时跳过 — 我稍后再开启通知", 'zh-TW': "暫時略過 — 我稍後再開啟通知" },
  "I Added It To My Home Screen, Re-Check": { 'zh-CN': "我已将其添加到主屏幕，重新检查", 'zh-TW': "我已將其新增到主畫面，重新檢查" },
  "This Browser Cannot Receive Notifications In A Tab. To Get Order Alerts, Add Pep Nation To Your Home Screen Using The Steps Above And Open It From The Icon. You Can Also Continue Now And Turn Notifications On Later From Your Dashboard.": { 'zh-CN': "此浏览器在标签页中无法接收通知。要获取订单提醒，请按上述步骤将 Pep Nation 添加到主屏幕并从图标打开。您也可以现在继续，稍后在控制台开启通知。", 'zh-TW': "此瀏覽器在分頁中無法接收通知。要取得訂單提醒，請按上述步驟將 Pep Nation 新增到主畫面並從圖示開啟。您也可以現在繼續，稍後在控制台開啟通知。" },
  "Reload": { 'zh-CN': "重新加载", 'zh-TW': "重新載入" },

  // ── Nav / chrome / footer ────────────────────────────────
  "Pep Nation Lab Home": { 'zh-CN': "Pep Nation Lab 首页", 'zh-TW': "Pep Nation Lab 首頁" },
  "Pep Nation Lab LLC. All Rights Reserved.": { 'zh-CN': "Pep Nation Lab LLC。保留所有权利。", 'zh-TW': "Pep Nation Lab LLC。保留所有權利。" },
  "Powered By": { 'zh-CN': "技术支持", 'zh-TW': "技術支援" },
  "Browse Catalog": { 'zh-CN': "浏览目录", 'zh-TW': "瀏覽目錄" },
  "Browse": { 'zh-CN': "浏览", 'zh-TW': "瀏覽" },
  "Admin Tools": { 'zh-CN': "管理工具", 'zh-TW': "管理工具" },
  "Administration": { 'zh-CN': "管理", 'zh-TW': "管理" },
  "Full Admin Panel": { 'zh-CN': "完整管理面板", 'zh-TW': "完整管理面板" },
  "You Are Signed In As": { 'zh-CN': "您当前登录身份为", 'zh-TW': "您目前登入身分為" },
  "Return To Catalog": { 'zh-CN': "返回目录", 'zh-TW': "返回目錄" },
  "Return To Store": { 'zh-CN': "返回店铺", 'zh-TW': "返回店鋪" },
  "Return To Store To Add Items": { 'zh-CN': "返回店铺添加商品", 'zh-TW': "返回店鋪新增商品" },
  "Back To": { 'zh-CN': "返回", 'zh-TW': "返回" },
  "Back To Dashboard": { 'zh-CN': "返回控制台", 'zh-TW': "返回控制台" },
  "Back To Store": { 'zh-CN': "返回店铺", 'zh-TW': "返回店鋪" },
  "Back To Agent Dashboard": { 'zh-CN': "返回代理控制台", 'zh-TW': "返回代理控制台" },
  "← Back": { 'zh-CN': "← 返回", 'zh-TW': "← 返回" },
  "← Back To Dashboard": { 'zh-CN': "← 返回控制台", 'zh-TW': "← 返回控制台" },
  "← Back To Agent Dashboard": { 'zh-CN': "← 返回代理控制台", 'zh-TW': "← 返回代理控制台" },
  "← Back to Storefront": { 'zh-CN': "← 返回店铺", 'zh-TW': "← 返回店鋪" },
  "← Back To Wallet": { 'zh-CN': "← 返回钱包", 'zh-TW': "← 返回錢包" },
  "← Previous": { 'zh-CN': "← 上一页", 'zh-TW': "← 上一頁" },
  "Next →": { 'zh-CN': "下一页 →", 'zh-TW': "下一頁 →" },
  "Coming Soon": { 'zh-CN': "即将推出", 'zh-TW': "即將推出" },
  "Account Language": { 'zh-CN': "账户语言", 'zh-TW': "帳戶語言" },
  "Sets The Language This Account Sees When They Log In.": { 'zh-CN': "设置此账户登录时看到的语言。", 'zh-TW': "設定此帳戶登入時看到的語言。" },
  "English": { 'zh-CN': "英语", 'zh-TW': "英語" },

  // ── Dashboard overview / KPIs ────────────────────────────
  "Command Center": { 'zh-CN': "指挥中心", 'zh-TW': "指揮中心" },
  "Your Agent Network": { 'zh-CN': "您的代理网络", 'zh-TW': "您的代理網路" },
  "My Agents": { 'zh-CN': "我的代理", 'zh-TW': "我的代理" },
  "My Downline": { 'zh-CN': "我的下线", 'zh-TW': "我的下線" },
  "My Referrals": { 'zh-CN': "我的推荐", 'zh-TW': "我的推薦" },
  "My Sales Profit": { 'zh-CN': "我的销售利润", 'zh-TW': "我的銷售利潤" },
  "Sub-Agent Dashboard": { 'zh-CN': "子代理控制台", 'zh-TW': "子代理控制台" },
  "Sub-Agent Rollup": { 'zh-CN': "子代理汇总", 'zh-TW': "子代理彙總" },
  "Downline Profit": { 'zh-CN': "下线利润", 'zh-TW': "下線利潤" },
  "Downline Balances": { 'zh-CN': "下线余额", 'zh-TW': "下線餘額" },
  "Downline Invoices": { 'zh-CN': "下线账单", 'zh-TW': "下線帳單" },
  "Network Orders — All Agents": { 'zh-CN': "网络订单 — 所有代理", 'zh-TW': "網路訂單 — 所有代理" },
  "Recent Order Activity": { 'zh-CN': "近期订单活动", 'zh-TW': "近期訂單活動" },
  "Activity Chart": { 'zh-CN': "活动图表", 'zh-TW': "活動圖表" },
  "Conversion Funnel": { 'zh-CN': "转化漏斗", 'zh-TW': "轉換漏斗" },
  "Where Visitors Drop Off On The Way To An Order.": { 'zh-CN': "访客在下单过程中流失的环节。", 'zh-TW': "訪客在下單過程中流失的環節。" },
  "Checkouts Started": { 'zh-CN': "已开始结账", 'zh-TW': "已開始結帳" },
  "Orders Completed": { 'zh-CN': "已完成订单", 'zh-TW': "已完成訂單" },
  "Conversion %": { 'zh-CN': "转化率 %", 'zh-TW': "轉換率 %" },
  "Unique Sessions": { 'zh-CN': "独立会话", 'zh-TW': "獨立工作階段" },
  "Pageviews": { 'zh-CN': "页面浏览量", 'zh-TW': "頁面瀏覽量" },
  "Views": { 'zh-CN': "浏览量", 'zh-TW': "瀏覽量" },
  "Top Viewed Products": { 'zh-CN': "浏览量最高的产品", 'zh-TW': "瀏覽量最高的產品" },
  "Top Search Terms": { 'zh-CN': "热门搜索词", 'zh-TW': "熱門搜尋詞" },
  "Top Researchers By Order Value": { 'zh-CN': "按订单金额排名的研究员", 'zh-TW': "按訂單金額排名的研究員" },
  "Attributed Orders": { 'zh-CN': "归因订单", 'zh-TW': "歸因訂單" },
  "Commissions Earned": { 'zh-CN': "已赚取佣金", 'zh-TW': "已賺取佣金" },
  "Lifetime Commission": { 'zh-CN': "累计佣金", 'zh-TW': "累計佣金" },
  "New Researchers": { 'zh-CN': "新研究员", 'zh-TW': "新研究員" },
  "Sold This Month": { 'zh-CN': "本月已售", 'zh-TW': "本月已售" },
  "This Week:": { 'zh-CN': "本周：", 'zh-TW': "本週：" },
  "This Month ·": { 'zh-CN': "本月 ·", 'zh-TW': "本月 ·" },
  "Higher Volume This Month": { 'zh-CN': "本月销量更高", 'zh-TW': "本月銷量更高" },
  "Total Researchers Tagged To You": { 'zh-CN': "已归属于您的研究员总数", 'zh-TW': "已歸屬於您的研究員總數" },

  // ── Wallet / statements / credit / invoices ──────────────
  "Your Balance, Invoices, And Payouts": { 'zh-CN': "您的余额、账单和结算", 'zh-TW': "您的餘額、帳單和結算" },
  "Wallet Sections": { 'zh-CN': "钱包板块", 'zh-TW': "錢包版塊" },
  "Real Funds You Can Send Or Spend Across The Network.": { 'zh-CN': "您可在网络中转账或消费的真实资金。", 'zh-TW': "您可在網路中轉帳或消費的真實資金。" },
  "Current Balance:": { 'zh-CN': "当前余额：", 'zh-TW': "目前餘額：" },
  "Prepaid Balance:": { 'zh-CN': "预付余额：", 'zh-TW': "預付餘額：" },
  "Credit Used:": { 'zh-CN': "已用信用额度：", 'zh-TW': "已用信用額度：" },
  "Current Limit: $": { 'zh-CN': "当前额度：$", 'zh-TW': "目前額度：$" },
  "Amount Due": { 'zh-CN': "应付金额", 'zh-TW': "應付金額" },
  "Total Due": { 'zh-CN': "应付总额", 'zh-TW': "應付總額" },
  "Bills To Pay": { 'zh-CN': "待付账单", 'zh-TW': "待付帳單" },
  "Pay Invoice": { 'zh-CN': "支付账单", 'zh-TW': "支付帳單" },
  "Invoice": { 'zh-CN': "账单", 'zh-TW': "帳單" },
  "Invoice History": { 'zh-CN': "账单历史", 'zh-TW': "帳單歷史" },
  "Open Invoices": { 'zh-CN': "未结账单", 'zh-TW': "未結帳單" },
  "Open Invoices:": { 'zh-CN': "未结账单：", 'zh-TW': "未結帳單：" },
  "No Open Invoices.": { 'zh-CN': "没有未结账单。", 'zh-TW': "沒有未結帳單。" },
  "No Invoices Yet.": { 'zh-CN': "暂无账单。", 'zh-TW': "暫無帳單。" },
  "Print Invoice": { 'zh-CN': "打印账单", 'zh-TW': "列印帳單" },
  "You Are All Paid Up.": { 'zh-CN': "您已全部结清。", 'zh-TW': "您已全部結清。" },
  "Next Statement": { 'zh-CN': "下期结算单", 'zh-TW': "下期結算單" },
  "Weekly Statements": { 'zh-CN': "每周结算单", 'zh-TW': "每週結算單" },
  "Orders In This Statement": { 'zh-CN': "本期结算单中的订单", 'zh-TW': "本期結算單中的訂單" },
  "No Statements Found. Statements Are Generated Weekly For Your Fulfillment Costs.": { 'zh-CN': "未找到结算单。结算单每周为您的履约成本生成一次。", 'zh-TW': "未找到結算單。結算單每週為您的履約成本生成一次。" },
  "These Statements Represent Your Wholesale Cost (COGS) And Shipping Costs Owed To The Admin For Fulfillment.": { 'zh-CN': "这些结算单代表您因履约而应付给管理方的批发成本（COGS）和运费。", 'zh-TW': "這些結算單代表您因履約而應付給管理方的批發成本（COGS）和運費。" },
  "Dispute Statement": { 'zh-CN': "对结算单提出异议", 'zh-TW': "對結算單提出異議" },
  "Describe What Looks Incorrect On This Statement": { 'zh-CN': "描述此结算单中看起来有误的地方", 'zh-TW': "描述此結算單中看起來有誤的地方" },
  "Reason For Dispute": { 'zh-CN': "异议原因", 'zh-TW': "異議原因" },
  "Auto-Pay": { 'zh-CN': "自动付款", 'zh-TW': "自動付款" },
  "When Enabled And Your Prepaid Balance Covers A Statement, It Is Paid Automatically Before The Due Date.": { 'zh-CN': "启用后，若您的预付余额足以支付某期结算单，将在到期日前自动付款。", 'zh-TW': "啟用後，若您的預付餘額足以支付某期結算單，將在到期日前自動付款。" },
  "Credit Cap": { 'zh-CN': "信用上限", 'zh-TW': "信用上限" },
  "Credit Increase Requests": { 'zh-CN': "提额申请", 'zh-TW': "提額申請" },
  "Request Credit Increase": { 'zh-CN': "申请提高额度", 'zh-TW': "申請提高額度" },
  "Requested Limit": { 'zh-CN': "申请额度", 'zh-TW': "申請額度" },
  "Credit Increase Available Once You Have An Active Credit Line.": { 'zh-CN': "拥有有效信用额度后即可申请提额。", 'zh-TW': "擁有有效信用額度後即可申請提額。" },
  "Credit Lines Are Virtual Caps. Your Own Admin-Assigned Credit Is The Real Ceiling.": { 'zh-CN': "信用额度为虚拟上限。管理方分配给您的信用额度才是真正的上限。", 'zh-TW': "信用額度為虛擬上限。管理方分配給您的信用額度才是真正的上限。" },
  "Send Funds": { 'zh-CN': "转账", 'zh-TW': "轉帳" },
  "Recipient": { 'zh-CN': "收款人", 'zh-TW': "收款人" },
  "Change Recipient": { 'zh-CN': "更改收款人", 'zh-TW': "更改收款人" },
  "Funds Are Deducted From Your Wallet (Or Billed To Your Credit Line) And Added To The Recipient's Wallet.": { 'zh-CN': "资金将从您的钱包扣除（或计入您的信用额度），并添加到收款人的钱包。", 'zh-TW': "資金將從您的錢包扣除（或計入您的信用額度），並新增到收款人的錢包。" },
  "Payment Received Via": { 'zh-CN': "收款方式", 'zh-TW': "收款方式" },
  "Payment Proof": { 'zh-CN': "付款凭证", 'zh-TW': "付款憑證" },
  "Payment Proofs Across All Orders.": { 'zh-CN': "所有订单的付款凭证。", 'zh-TW': "所有訂單的付款憑證。" },
  "Preferred Payout Handle": { 'zh-CN': "首选收款账号", 'zh-TW': "首選收款帳號" },
  "Payment Handle": { 'zh-CN': "收款账号", 'zh-TW': "收款帳號" },
  "Copy Payment Handle": { 'zh-CN': "复制收款账号", 'zh-TW': "複製收款帳號" },
  "Copy Amount Due": { 'zh-CN': "复制应付金额", 'zh-TW': "複製應付金額" },
  "Settled": { 'zh-CN': "已结算", 'zh-TW': "已結算" },
  "Overdue": { 'zh-CN': "已逾期", 'zh-TW': "已逾期" },
  "Grace Period Active": { 'zh-CN': "宽限期生效中", 'zh-TW': "寬限期生效中" },
  "Freeze": { 'zh-CN': "冻结", 'zh-TW': "凍結" },
  "Freeze Transactions": { 'zh-CN': "冻结交易", 'zh-TW': "凍結交易" },
  "TRANSACTIONS FROZEN": { 'zh-CN': "交易已冻结", 'zh-TW': "交易已凍結" },
  "Recent Settlements": { 'zh-CN': "近期结算", 'zh-TW': "近期結算" },
  "No Settlements Yet.": { 'zh-CN': "暂无结算。", 'zh-TW': "暫無結算。" },
  "Receipt": { 'zh-CN': "收据", 'zh-TW': "收據" },
  "Receipt Vault": { 'zh-CN': "收据库", 'zh-TW': "收據庫" },
  "Open Receipt": { 'zh-CN': "打开收据", 'zh-TW': "開啟收據" },
  "No Receipts Yet.": { 'zh-CN': "暂无收据。", 'zh-TW': "暫無收據。" },

  // ── Cart / checkout ──────────────────────────────────────
  "Your Cart (": { 'zh-CN': "您的购物车（", 'zh-TW': "您的購物車（" },
  "Your Shopping Cart Is Empty": { 'zh-CN': "您的购物车是空的", 'zh-TW': "您的購物車是空的" },
  "Cart Is Empty. Add Products Above.": { 'zh-CN': "购物车为空。请在上方添加产品。", 'zh-TW': "購物車為空。請在上方新增產品。" },
  "Add To Cart": { 'zh-CN': "加入购物车", 'zh-TW': "加入購物車" },
  "Add Research Compounds From The Catalog To Proceed.": { 'zh-CN': "请从目录中添加研究化合物以继续。", 'zh-TW': "請從目錄中新增研究化合物以繼續。" },
  "Continue To Payment": { 'zh-CN': "继续付款", 'zh-TW': "繼續付款" },
  "Continue To Terms": { 'zh-CN': "继续查看条款", 'zh-TW': "繼續查看條款" },
  "Secure Order Checkout": { 'zh-CN': "安全订单结账", 'zh-TW': "安全訂單結帳" },
  "Customer And Shipping Details": { 'zh-CN': "客户与配送信息", 'zh-TW': "客戶與配送資訊" },
  "Shipping Delivery Address": { 'zh-CN': "配送地址", 'zh-TW': "配送地址" },
  "Fulfillment Method": { 'zh-CN': "履约方式", 'zh-TW': "履約方式" },
  "Use A New Address": { 'zh-CN': "使用新地址", 'zh-TW': "使用新地址" },
  "Save This Address To My Account For Future Orders.": { 'zh-CN': "将此地址保存到我的账户，以便日后下单使用。", 'zh-TW': "將此地址儲存到我的帳戶，以便日後下單使用。" },
  "Coupon": { 'zh-CN': "优惠券", 'zh-TW': "優惠券" },
  "Coupon Code": { 'zh-CN': "优惠券代码", 'zh-TW': "優惠券代碼" },
  "Coupon Discount": { 'zh-CN': "优惠券折扣", 'zh-TW': "優惠券折扣" },
  "Bundle Price": { 'zh-CN': "套装价格", 'zh-TW': "套裝價格" },
  "Bundle Price Applied": { 'zh-CN': "已应用套装价格", 'zh-TW': "已套用套裝價格" },
  "Bundle Savings": { 'zh-CN': "套装节省", 'zh-TW': "套裝節省" },
  "Products Included": { 'zh-CN': "包含产品", 'zh-TW': "包含產品" },
  "Regular Price": { 'zh-CN': "原价", 'zh-TW': "原價" },
  "If Bought Separately:": { 'zh-CN': "若单独购买：", 'zh-TW': "若單獨購買：" },
  "Shipping Cost ($)": { 'zh-CN': "运费（$）", 'zh-TW': "運費（$）" },
  "Order Items": { 'zh-CN': "订单商品", 'zh-TW': "訂單商品" },
  "Order Minimum Not Met:": { 'zh-CN': "未达到最低订单要求：", 'zh-TW': "未達到最低訂單要求：" },
  "This Storefront Requires An Overall Minimum Order Of": { 'zh-CN': "此店铺要求整体最低订单额为", 'zh-TW': "此店鋪要求整體最低訂單額為" },
  "Minimum Items - Add": { 'zh-CN': "最低商品数 - 添加", 'zh-TW': "最低商品數 - 新增" },
  "Placing Order": { 'zh-CN': "正在下单", 'zh-TW': "正在下單" },
  "Order Placed Successfully": { 'zh-CN': "订单已成功提交", 'zh-TW': "訂單已成功提交" },
  "Your Confirmed Order Total Is": { 'zh-CN': "您确认的订单总额为", 'zh-TW': "您確認的訂單總額為" },
  "Your Order Contains": { 'zh-CN': "您的订单包含", 'zh-TW': "您的訂單包含" },
  "We Reviewed Your Order:": { 'zh-CN': "我们已审核您的订单：", 'zh-TW': "我們已審核您的訂單：" },
  "Total Was Adjusted": { 'zh-CN': "总额已调整", 'zh-TW': "總額已調整" },
  "Your Research Order Has Been Registered And Is Awaiting Offline Payment.": { 'zh-CN': "您的研究订单已登记，正在等待线下付款。", 'zh-TW': "您的研究訂單已登記，正在等待線下付款。" },
  "Awaiting Your Payment Confirmation": { 'zh-CN': "等待您确认付款", 'zh-TW': "等待您確認付款" },
  "Your Cart Prices May Be Outdated.": { 'zh-CN': "您的购物车价格可能已过期。", 'zh-TW': "您的購物車價格可能已過期。" },
  "This Cart Was Loaded More Than # Hours Ago. Return To The Storefront To Refresh Prices Before Completing Your Order.": { 'zh-CN': "此购物车加载已超过 # 小时。请返回店铺刷新价格后再完成下单。", 'zh-TW': "此購物車載入已超過 # 小時。請返回店鋪重新整理價格後再完成下單。" },
  "Select New Payment Method": { 'zh-CN': "选择新的付款方式", 'zh-TW': "選擇新的付款方式" },
  "Change Method": { 'zh-CN': "更改方式", 'zh-TW': "更改方式" },
  "Amount Is Server-Verified. Mismatch Will Reject The Payment.": { 'zh-CN': "金额由服务器核验。不一致将导致付款被拒。", 'zh-TW': "金額由伺服器核驗。不一致將導致付款被拒。" },
  "Copy Order ID": { 'zh-CN': "复制订单编号", 'zh-TW': "複製訂單編號" },
  "Order Identifier": { 'zh-CN': "订单标识", 'zh-TW': "訂單標識" },
  "Order:": { 'zh-CN': "订单：", 'zh-TW': "訂單：" },
  "To The Payment Handle Below.": { 'zh-CN': "至下方的收款账号。", 'zh-TW': "至下方的收款帳號。" },
  "Select Your Preferred Offline Channel To Finalize Cash Settlement. Our Staff Will Release Your Lab Experimentation Order Instantly Upon Verifying Receipt.": { 'zh-CN': "选择您偏好的线下渠道以完成现金结算。我们的工作人员在核实收款后将立即放行您的实验订单。", 'zh-TW': "選擇您偏好的線下管道以完成現金結算。我們的工作人員在核實收款後將立即放行您的實驗訂單。" },
  "Your Checkout Complete Order ID Will Be Displayed Following Submission. Simply Complete Payment Settlement Via The Listed Handle And Input Your Order ID In The Payment Reference.": { 'zh-CN': "提交后将显示您的完整结账订单编号。只需通过所列账号完成付款结算，并在付款备注中填写您的订单编号即可。", 'zh-TW': "提交後將顯示您的完整結帳訂單編號。只需透過所列帳號完成付款結算，並在付款備註中填寫您的訂單編號即可。" },
  "Payment Process Notice": { 'zh-CN': "付款流程须知", 'zh-TW': "付款流程須知" },
  "You Have Opted For Manual In-Person Pickup. No Package Shipping Fee Will Be Charged. Please Arrange Coordinates With Your Local Partner Following Order Placement.": { 'zh-CN': "您已选择手动当面取货。将不收取包裹运费。请在下单后与您的本地合作方安排取货事宜。", 'zh-TW': "您已選擇手動當面取貨。將不收取包裹運費。請在下單後與您的本地合作方安排取貨事宜。" },

  // ── Account settings / profile / security ────────────────
  "Account Sections": { 'zh-CN': "账户板块", 'zh-TW': "帳戶版塊" },
  "Profile Details": { 'zh-CN': "个人资料", 'zh-TW': "個人資料" },
  "Manage Your Personal Information, Avatar, And Username.": { 'zh-CN': "管理您的个人信息、头像和用户名。", 'zh-TW': "管理您的個人資訊、頭像和使用者名稱。" },
  "Manage Your Profile, Sign-In Security, Notifications, And Compliance Status.": { 'zh-CN': "管理您的个人资料、登录安全、通知和合规状态。", 'zh-TW': "管理您的個人資料、登入安全、通知和合規狀態。" },
  "Manage your network, agents, and the full platform.": { 'zh-CN': "管理您的网络、代理和整个平台。", 'zh-TW': "管理您的網路、代理和整個平台。" },
  "Display Name": { 'zh-CN': "显示名称", 'zh-TW': "顯示名稱" },
  "Change Username": { 'zh-CN': "更改用户名", 'zh-TW': "更改使用者名稱" },
  "New Username": { 'zh-CN': "新用户名", 'zh-TW': "新使用者名稱" },
  "Username *": { 'zh-CN': "用户名 *", 'zh-TW': "使用者名稱 *" },
  "You Can Change Your Username Again In": { 'zh-CN': "您可以再次更改用户名的时间：", 'zh-TW': "您可以再次更改使用者名稱的時間：" },
  "Lowercase Letters, Numbers, And Underscores Only. You Can Only Change This Once Every": { 'zh-CN': "仅限小写字母、数字和下划线。此项每隔一段时间只能更改一次：", 'zh-TW': "僅限小寫字母、數字和底線。此項每隔一段時間只能更改一次：" },
  "Per-Event Channels": { 'zh-CN': "各事件通知渠道", 'zh-TW': "各事件通知管道" },
  "Choose Which Events Reach You And On Which Channel. Email Is Currently Disabled Platform-Wide.": { 'zh-CN': "选择哪些事件通知您以及通过哪个渠道。电子邮件目前在全平台已停用。", 'zh-TW': "選擇哪些事件通知您以及透過哪個管道。電子郵件目前在全平台已停用。" },
  "Quiet Hours": { 'zh-CN': "免打扰时段", 'zh-TW': "勿擾時段" },
  "Mute All Notifications For # Hours": { 'zh-CN': "静音所有通知 # 小时", 'zh-TW': "靜音所有通知 # 小時" },
  "Unmute Now (Muted Until": { 'zh-CN': "立即取消静音（静音至", 'zh-TW': "立即取消靜音（靜音至" },
  "Notifications Will Be Silenced On This Device During The Window Below. Stored Locally In Your Browser.": { 'zh-CN': "在下方时段内，此设备上的通知将被静音。设置存储在您的浏览器本地。", 'zh-TW': "在下方時段內，此裝置上的通知將被靜音。設定儲存在您的瀏覽器本機。" },
  "In-App": { 'zh-CN': "应用内", 'zh-TW': "應用程式內" },
  "Push": { 'zh-CN': "推送", 'zh-TW': "推播" },
  "No Active Sessions Tracked Yet. Your Current Browser Will Appear Here After The Next Sign-In.": { 'zh-CN': "尚未追踪到活动会话。您当前的浏览器将在下次登录后显示在此处。", 'zh-TW': "尚未追蹤到活動工作階段。您目前的瀏覽器將在下次登入後顯示在此處。" },
  "Last Seen": { 'zh-CN': "最后活跃", 'zh-TW': "最後活躍" },
  "Download Your Data": { 'zh-CN': "下载您的数据", 'zh-TW': "下載您的資料" },
  "Request A Bundle Of Your Profile, Orders, Addresses, And Messages. Exports Are Prepared In The Background And Appear Below When They Are Ready.": { 'zh-CN': "申请打包您的个人资料、订单、地址和消息。导出将在后台准备，就绪后显示在下方。", 'zh-TW': "申請打包您的個人資料、訂單、地址和訊息。匯出將在背景準備，就緒後顯示在下方。" },
  "Recent Exports": { 'zh-CN': "近期导出", 'zh-TW': "近期匯出" },
  "No Export Requests Yet.": { 'zh-CN': "暂无导出请求。", 'zh-TW': "暫無匯出請求。" },
  "Deactivate Account": { 'zh-CN': "停用账户", 'zh-TW': "停用帳戶" },
  "Deactivate My Account": { 'zh-CN': "停用我的账户", 'zh-TW': "停用我的帳戶" },
  "Deactivating Hides Your Storefront, Disables Future Sign-Ins, And Signs You Out Everywhere. Your Order History Is Preserved. Contact Support To Restore An Account.": { 'zh-CN': "停用后将隐藏您的店铺、禁止日后登录，并在所有设备上退出登录。您的订单历史将予以保留。如需恢复账户，请联系支持团队。", 'zh-TW': "停用後將隱藏您的店鋪、禁止日後登入，並在所有裝置上登出。您的訂單歷史將予以保留。如需復原帳戶，請聯絡支援團隊。" },
  "Once Deactivated, You Will Need Admin Help To Restore Access. Your Storefront Will Go Offline Immediately.": { 'zh-CN': "一旦停用，您将需要管理员协助才能恢复访问。您的店铺将立即下线。", 'zh-TW': "一旦停用，您將需要管理員協助才能復原存取。您的店鋪將立即下線。" },

  // ── Agents / sub-agents / referrals management ───────────
  "Create Agent": { 'zh-CN': "创建代理", 'zh-TW': "建立代理" },
  "Quick Create Agent": { 'zh-CN': "快速创建代理", 'zh-TW': "快速建立代理" },
  "Go to Create Agent Form": { 'zh-CN': "前往创建代理表单", 'zh-TW': "前往建立代理表單" },
  "Create your first agent →": { 'zh-CN': "创建您的第一个代理 →", 'zh-TW': "建立您的第一個代理 →" },
  "Recruit Agents": { 'zh-CN': "招募代理", 'zh-TW': "招募代理" },
  "Recruit New Agents": { 'zh-CN': "招募新代理", 'zh-TW': "招募新代理" },
  "Make Super Agent": { 'zh-CN': "设为超级代理", 'zh-TW': "設為超級代理" },
  "Sub Agent": { 'zh-CN': "子代理", 'zh-TW': "子代理" },
  "Sub Agents (": { 'zh-CN': "子代理（", 'zh-TW': "子代理（" },
  "Your Sub-Agents": { 'zh-CN': "您的子代理", 'zh-TW': "您的子代理" },
  "You Have No Sub-Agents Yet.": { 'zh-CN': "您还没有子代理。", 'zh-TW': "您還沒有子代理。" },
  "Promote New Sub-Agent": { 'zh-CN': "提拔新子代理", 'zh-TW': "提拔新子代理" },
  "Promote A Researcher To Sub-Agent": { 'zh-CN': "将研究员提拔为子代理", 'zh-TW': "將研究員提拔為子代理" },
  "Promote A Researcher From Your Downline To Get Started. Sub-Agents Sell On Your Storefront At Your Prices And Earn A Commission Percentage Of Total Sales, Settled As Digital Credits Every Sunday Night.": { 'zh-CN': "从您的下线中提拔一名研究员即可开始。子代理以您的价格在您的店铺销售，并赚取总销售额一定比例的佣金，每周日晚以数字信用额度结算。", 'zh-TW': "從您的下線中提拔一名研究員即可開始。子代理以您的價格在您的店鋪銷售，並賺取總銷售額一定比例的佣金，每週日晚以數位信用額度結算。" },
  "You Have No Researchers In Your Downline Yet. Add Researchers Via Your Storefront Before Promoting.": { 'zh-CN': "您的下线中还没有研究员。请先通过您的店铺添加研究员，然后再进行提拔。", 'zh-TW': "您的下線中還沒有研究員。請先透過您的店鋪新增研究員，然後再進行提拔。" },
  "Sub-Agents Sell On Your Storefront At Your Prices And Earn A Commission Percentage Of Total Sales. You Set The Commission Rate (Up To #), Decide Whether They Run On A Credit Line Or Prepaid Balance, And Cap Their Credit. Commission Accrues On Every Order And Settles To Their Account As Digital Credits Every Sunday Night.": { 'zh-CN': "子代理以您的价格在您的店铺销售，并赚取总销售额一定比例的佣金。您设定佣金费率（最高 #），决定他们使用信用额度还是预付余额，并为其信用额度设定上限。佣金按每笔订单累计，每周日晚以数字信用额度结算到他们的账户。", 'zh-TW': "子代理以您的價格在您的店鋪銷售，並賺取總銷售額一定比例的佣金。您設定佣金費率（最高 #），決定他們使用信用額度還是預付餘額，並為其信用額度設定上限。佣金按每筆訂單累計，每週日晚以數位信用額度結算到他們的帳戶。" },
  "Commission % (Of Sales)": { 'zh-CN': "佣金 %（占销售额）", 'zh-TW': "佣金 %（佔銷售額）" },
  "Commission Percentage (% Of Total Sales):": { 'zh-CN': "佣金百分比（占总销售额 %）：", 'zh-TW': "佣金百分比（佔總銷售額 %）：" },
  "Base Commission %": { 'zh-CN': "基础佣金 %", 'zh-TW': "基礎佣金 %" },
  "Commission Plan": { 'zh-CN': "佣金方案", 'zh-TW': "佣金方案" },
  "Your Commission Tier": { 'zh-CN': "您的佣金等级", 'zh-TW': "您的佣金等級" },
  "Virtual Credit Cap (Dollars)": { 'zh-CN': "虚拟信用上限（美元）", 'zh-TW': "虛擬信用上限（美元）" },
  "How Much Of Their Sales Can Sit Unpaid To You Before They're Blocked At Checkout.": { 'zh-CN': "在其结账被拦截之前，他们可有多少未付给您的销售额。", 'zh-TW': "在其結帳被攔截之前，他們可有多少未付給您的銷售額。" },
  "Performance Bonus Milestones": { 'zh-CN': "绩效奖金里程碑", 'zh-TW': "績效獎金里程碑" },
  "Add Milestone": { 'zh-CN': "添加里程碑", 'zh-TW': "新增里程碑" },
  "No Milestones. Add One Or Leave Empty To Use The House Default.": { 'zh-CN': "暂无里程碑。添加一个，或留空以使用系统默认值。", 'zh-TW': "暫無里程碑。新增一個，或留空以使用系統預設值。" },
  "When Monthly Retail Reaches A Milestone, The Bonus Is Added To The Base Rate (Capped At Max).": { 'zh-CN': "当月零售额达到某个里程碑时，奖金将加到基础费率上（以最高上限为限）。", 'zh-TW': "當月零售額達到某個里程碑時，獎金將加到基礎費率上（以最高上限為限）。" },
  "Max Cap % (Optional)": { 'zh-CN': "最高上限 %（可选）", 'zh-TW': "最高上限 %（選填）" },
  "Velocity Cap $ (Optional)": { 'zh-CN': "速率上限 $（可选）", 'zh-TW': "速率上限 $（選填）" },
  ". Set Their Base Rate, Optional Max Cap, Velocity Cap, And Performance-Bonus Milestones.": { 'zh-CN': "。设置其基础费率、可选的最高上限、速率上限和绩效奖金里程碑。", 'zh-TW': "。設定其基礎費率、可選的最高上限、速率上限和績效獎金里程碑。" },
  "Revoke Agent Privileges For": { 'zh-CN': "撤销代理权限：", 'zh-TW': "撤銷代理權限：" },
  "Revoke Invitation": { 'zh-CN': "撤销邀请", 'zh-TW': "撤銷邀請" },
  "Refresh Invitations": { 'zh-CN': "刷新邀请", 'zh-TW': "重新整理邀請" },
  "Sent Invitations": { 'zh-CN': "已发送的邀请", 'zh-TW': "已傳送的邀請" },
  "No Invitations Yet. Create One Above To Start Building Your Downline.": { 'zh-CN': "暂无邀请。在上方创建一个，开始建立您的下线。", 'zh-TW': "暫無邀請。在上方建立一個，開始建立您的下線。" },
  "Send A One-Time Link That Lets A New Agent Set Their Password And Join Your Downline With The Role And Tier You Choose.": { 'zh-CN': "发送一个一次性链接，让新代理设置密码，并以您选择的角色和等级加入您的下线。", 'zh-TW': "傳送一個一次性連結，讓新代理設定密碼，並以您選擇的角色和等級加入您的下線。" },
  "Give This Link To Your Sub-Agent. Any New Researcher Who Signs Up Through It Gets Tagged To Them, And Every Order That Researcher Places Earns The Sub-Agent A Commission.": { 'zh-CN': "将此链接交给您的子代理。任何通过它注册的新研究员都会归属于该子代理，且该研究员下的每笔订单都会为子代理赚取佣金。", 'zh-TW': "將此連結交給您的子代理。任何透過它註冊的新研究員都會歸屬於該子代理，且該研究員下的每筆訂單都會為子代理賺取佣金。" },
  "Your Sub-Agent's Invite Link": { 'zh-CN': "您子代理的邀请链接", 'zh-TW': "您子代理的邀請連結" },
  "Your Referral Link": { 'zh-CN': "您的推荐链接", 'zh-TW': "您的推薦連結" },
  "Your Referral Invite Link": { 'zh-CN': "您的推荐邀请链接", 'zh-TW': "您的推薦邀請連結" },
  "Referral QR": { 'zh-CN': "推荐二维码", 'zh-TW': "推薦 QR 碼" },
  "Referral QR Code": { 'zh-CN': "推荐二维码", 'zh-TW': "推薦 QR 碼" },
  "Show QR Code": { 'zh-CN': "显示二维码", 'zh-TW': "顯示 QR 碼" },
  "Your QR code": { 'zh-CN': "您的二维码", 'zh-TW': "您的 QR 碼" },
  "QR code not available. Contact admin.": { 'zh-CN': "二维码不可用。请联系管理员。", 'zh-TW': "QR 碼不可用。請聯絡管理員。" },
  "Share This Link With New Researchers. Sign-Ups Through This Link Are Permanently Tagged To You And Earn You Commission On Every Order.": { 'zh-CN': "将此链接分享给新研究员。通过此链接注册的用户将永久归属于您，并让您从每笔订单中赚取佣金。", 'zh-TW': "將此連結分享給新研究員。透過此連結註冊的使用者將永久歸屬於您，並讓您從每筆訂單中賺取佣金。" },
  "Share This QR Code In Person Or Digitally. Researchers Who Sign Up Via Your Link Or QR Code Are Automatically Added To Your Downline.": { 'zh-CN': "当面或以数字方式分享此二维码。通过您的链接或二维码注册的研究员将自动加入您的下线。", 'zh-TW': "當面或以數位方式分享此 QR 碼。透過您的連結或 QR 碼註冊的研究員將自動加入您的下線。" },
  "Share Your Unique Invite Link To Recruit Researchers To Your Storefront.": { 'zh-CN': "分享您专属的邀请链接，为您的店铺招募研究员。", 'zh-TW': "分享您專屬的邀請連結，為您的店鋪招募研究員。" },
  "Share your referral QR or link so new agents join directly under your network. Manage everyone from the Agents tool above.": { 'zh-CN': "分享您的推荐二维码或链接，让新代理直接加入您的网络。可在上方的“代理”工具中管理所有人。", 'zh-TW': "分享您的推薦 QR 碼或連結，讓新代理直接加入您的網路。可在上方的「代理」工具中管理所有人。" },
  "Share your storefront link or QR code to recruit agents under your brand. Any agent who signs up through your link will be connected to your network.": { 'zh-CN': "分享您的店铺链接或二维码，在您的品牌下招募代理。任何通过您的链接注册的代理都将加入您的网络。", 'zh-TW': "分享您的店鋪連結或 QR 碼，在您的品牌下招募代理。任何透過您的連結註冊的代理都將加入您的網路。" },
  "You Must Complete Your Storefront Setup Before A Referral Link Is Generated.": { 'zh-CN': "在生成推荐链接之前，您必须先完成店铺设置。", 'zh-TW': "在生成推薦連結之前，您必須先完成店鋪設定。" },
  "No agents yet.": { 'zh-CN': "暂无代理。", 'zh-TW': "暫無代理。" },
  "No agents yet. Create your first agent above.": { 'zh-CN': "暂无代理。在上方创建您的第一个代理。", 'zh-TW': "暫無代理。在上方建立您的第一個代理。" },
  "No agents match your search.": { 'zh-CN': "没有符合您搜索的代理。", 'zh-TW': "沒有符合您搜尋的代理。" },
  "No Matches. Try Another Name, Username, Or Email.": { 'zh-CN': "无匹配结果。请尝试其他姓名、用户名或电子邮箱。", 'zh-TW': "無相符結果。請嘗試其他姓名、使用者名稱或電子郵件。" },
  "Team Org Chart": { 'zh-CN': "团队组织架构图", 'zh-TW': "團隊組織架構圖" },
  "Your Agents, Their Researchers, And Yours. Move Any Researcher To Any Account In Your Downline.": { 'zh-CN': "您的代理、他们的研究员以及您自己的研究员。可将任何研究员移动到您下线中的任何账户。", 'zh-TW': "您的代理、他們的研究員以及您自己的研究員。可將任何研究員移動到您下線中的任何帳戶。" },
  "Broadcast To Network": { 'zh-CN': "向网络广播", 'zh-TW': "向網路廣播" },
  "Broadcast To Researchers": { 'zh-CN': "向研究员广播", 'zh-TW': "向研究員廣播" },
  "Recent Broadcasts": { 'zh-CN': "近期广播", 'zh-TW': "近期廣播" },
  "No Broadcasts Yet. Send Your First Announcement Above.": { 'zh-CN': "暂无广播。在上方发送您的第一条公告。", 'zh-TW': "暫無廣播。在上方傳送您的第一則公告。" },
  "Send An Announcement To Every Active Researcher In Your Downline. They Receive It In-App And As A Push Notification.": { 'zh-CN': "向您下线中的每位活跃研究员发送公告。他们将通过应用内和推送通知收到。", 'zh-TW': "向您下線中的每位活躍研究員傳送公告。他們將透過應用程式內和推播通知收到。" },
  "Message body...": { 'zh-CN': "消息正文…", 'zh-TW': "訊息內文…" },

  // ── Storefront config / theme ────────────────────────────
  "Storefront Theme": { 'zh-CN': "店铺主题", 'zh-TW': "店鋪主題" },
  "Storefront Paused": { 'zh-CN': "店铺已暂停", 'zh-TW': "店鋪已暫停" },
  "Storefront Slug *": { 'zh-CN': "店铺网址后缀 *", 'zh-TW': "店鋪網址後綴 *" },
  "Your Store Name": { 'zh-CN': "您的店铺名称", 'zh-TW': "您的店鋪名稱" },
  "Your Storefront Tagline": { 'zh-CN': "您的店铺标语", 'zh-TW': "您的店鋪標語" },
  "Your Storefront Link": { 'zh-CN': "您的店铺链接", 'zh-TW': "您的店鋪連結" },
  "Open Live Storefront": { 'zh-CN': "打开线上店铺", 'zh-TW': "開啟線上店鋪" },
  "Tagline": { 'zh-CN': "标语", 'zh-TW': "標語" },
  "Shown on storefront": { 'zh-CN': "显示在店铺上", 'zh-TW': "顯示在店鋪上" },
  "Hero Image URL": { 'zh-CN': "主图 URL", 'zh-TW': "主圖 URL" },
  "Hero preview": { 'zh-CN': "主图预览", 'zh-TW': "主圖預覽" },
  "Live Preview": { 'zh-CN': "实时预览", 'zh-TW': "即時預覽" },
  "Primary Color": { 'zh-CN': "主色", 'zh-TW': "主色" },
  "Secondary Color": { 'zh-CN': "辅色", 'zh-TW': "輔色" },
  "Accent": { 'zh-CN': "强调色", 'zh-TW': "強調色" },
  "Accent Color": { 'zh-CN': "强调色", 'zh-TW': "強調色" },
  "Light": { 'zh-CN': "浅色", 'zh-TW': "淺色" },
  "Custom Domains": { 'zh-CN': "自定义域名", 'zh-TW': "自訂網域" },
  "No Custom Domains.": { 'zh-CN': "无自定义域名。", 'zh-TW': "無自訂網域。" },
  "Point Your Domain CNAME To pepnationlab.com - Approval Required.": { 'zh-CN': "将您域名的 CNAME 指向 pepnationlab.com — 需要审批。", 'zh-TW': "將您網域的 CNAME 指向 pepnationlab.com — 需要審批。" },
  "Open Full Account Settings →": { 'zh-CN': "打开完整账户设置 →", 'zh-TW': "開啟完整帳戶設定 →" },
  ". Keep It As Is, Or Change It To Something Custom - You Can Update Your User Name, Colors, And Payment Methods Below. This Banner Will Hide Once You Save The Page.": { 'zh-CN': "。保持原样，或改成自定义内容 — 您可在下方更新您的用户名、颜色和收款方式。保存页面后此横幅将隐藏。", 'zh-TW': "。保持原樣，或改成自訂內容 — 您可在下方更新您的使用者名稱、顏色和收款方式。儲存頁面後此橫幅將隱藏。" },

  // ── Orders / reorders / history ──────────────────────────
  "Order History And Reorders": { 'zh-CN': "订单历史与再次订购", 'zh-TW': "訂單歷史與再次訂購" },
  "Browse Your Past Orders. Tap Reorder To Add A Past Order Back To Your Cart, Then Review, Edit, And Add More Before Checkout.": { 'zh-CN': "浏览您的历史订单。点击“再次订购”可将历史订单重新加入购物车，然后在结账前查看、编辑并添加更多商品。", 'zh-TW': "瀏覽您的歷史訂單。點擊「再次訂購」可將歷史訂單重新加入購物車，然後在結帳前查看、編輯並新增更多商品。" },
  "No Past Orders Yet": { 'zh-CN': "暂无历史订单", 'zh-TW': "暫無歷史訂單" },
  "Once You Place An Order It Will Appear Here For Easy Reordering.": { 'zh-CN': "下单后，订单将显示在此处，方便再次订购。", 'zh-TW': "下單後，訂單將顯示在此處，方便再次訂購。" },
  "No Orders Found.": { 'zh-CN': "未找到订单。", 'zh-TW': "未找到訂單。" },
  "No orders found from your agents yet.": { 'zh-CN': "尚未找到来自您代理的订单。", 'zh-TW': "尚未找到來自您代理的訂單。" },
  "No Orders From Referred Researchers Yet.": { 'zh-CN': "尚无来自推荐研究员的订单。", 'zh-TW': "尚無來自推薦研究員的訂單。" },
  "No Orders Yet. Start Sharing Your Referral Link.": { 'zh-CN': "暂无订单。开始分享您的推荐链接吧。", 'zh-TW': "暫無訂單。開始分享您的推薦連結吧。" },
  "Could Not Load Your Orders. Please Try Again.": { 'zh-CN': "无法加载您的订单。请重试。", 'zh-TW': "無法載入您的訂單。請重試。" },
  "Order Inventory": { 'zh-CN': "订购库存", 'zh-TW': "訂購庫存" },
  "View Order Status": { 'zh-CN': "查看订单状态", 'zh-TW': "查看訂單狀態" },
  "Your Last Order Was": { 'zh-CN': "您上次下单于", 'zh-TW': "您上次下單於" },
  "Your Order Has Been Registered And Is Awaiting Offline Payment.": { 'zh-CN': "您的订单已登记，正在等待线下付款。", 'zh-TW': "您的訂單已登記，正在等待線下付款。" },
  "Print Labels": { 'zh-CN': "打印标签", 'zh-TW': "列印標籤" },
  "Print Now": { 'zh-CN': "立即打印", 'zh-TW': "立即列印" },
  "Print Mode": { 'zh-CN': "打印模式", 'zh-TW': "列印模式" },
  "Label Size": { 'zh-CN': "标签尺寸", 'zh-TW': "標籤尺寸" },
  "Search Labels": { 'zh-CN': "搜索标签", 'zh-TW': "搜尋標籤" },
  "No Labels Match Your Search.": { 'zh-CN': "没有符合您搜索的标签。", 'zh-TW': "沒有符合您搜尋的標籤。" },
  "Select Any Labels And Quantities, Pick A Label Size, Then Print. Labels Are Color-Coded By Research Category.": { 'zh-CN': "选择任意标签和数量，挑选标签尺寸，然后打印。标签按研究类别用颜色区分。", 'zh-TW': "選擇任意標籤和數量，挑選標籤尺寸，然後列印。標籤按研究類別用顏色區分。" },
  "Create Manual Shipment Order": { 'zh-CN': "创建手动发货订单", 'zh-TW': "建立手動發貨訂單" },

  // ── Tier / rewards / volume ──────────────────────────────
  "Current Tier": { 'zh-CN': "当前等级", 'zh-TW': "目前等級" },
  "Your Tier": { 'zh-CN': "您的等级", 'zh-TW': "您的等級" },
  "Pricing Tier": { 'zh-CN': "定价等级", 'zh-TW': "定價等級" },
  "Tier Ladder": { 'zh-CN': "等级阶梯", 'zh-TW': "等級階梯" },
  "Tier Rewards Program": { 'zh-CN': "等级奖励计划", 'zh-TW': "等級獎勵計劃" },
  "Tier # (Best Pricing)": { 'zh-CN': "第 # 级（最优价格）", 'zh-TW': "第 # 級（最優價格）" },
  "Tier # (Entry)": { 'zh-CN': "第 # 级（入门）", 'zh-TW': "第 # 級（入門）" },
  "Unlock Exclusive Pricing Tiers Based On Your Monthly Sales Volume. Higher Tiers Earn Better Margins And Priority Support.": { 'zh-CN': "根据您的月销量解锁专属定价等级。等级越高，利润越高，并享有优先支持。", 'zh-TW': "根據您的月銷量解鎖專屬定價等級。等級越高，利潤越高，並享有優先支援。" },
  "You Have Reached The Top Tier - Maximum Pricing Advantage Active": { 'zh-CN': "您已达到最高等级 — 最大定价优势已生效", 'zh-TW': "您已達到最高等級 — 最大定價優勢已生效" },
  "You're At The Top Tier And Have The Best Agent Cost Unlocked.": { 'zh-CN': "您已处于最高等级，并已解锁最优代理成本。", 'zh-TW': "您已處於最高等級，並已解鎖最優代理成本。" },
  "You've Unlocked Every Performance Bonus This Month.": { 'zh-CN': "您本月已解锁所有绩效奖金。", 'zh-TW': "您本月已解鎖所有績效獎金。" },
  "And Lower Your Agent Cost.": { 'zh-CN': "并降低您的代理成本。", 'zh-TW': "並降低您的代理成本。" },
  "In Volume Over The Last # Days": { 'zh-CN': "过去 # 天的销量", 'zh-TW': "過去 # 天的銷量" },
  "Your #-day volume has dropped below the minimum required for the": { 'zh-CN': "您 # 天的销量已跌破所需的最低门槛", 'zh-TW': "您 # 天的銷量已跌破所需的最低門檻" },
  "in volume, or you will be demoted to your earned tier and your prices will increase.": { 'zh-CN': "的销量，否则您将被降至您应得的等级，价格也会上涨。", 'zh-TW': "的銷量，否則您將被降至您應得的等級，價格也會上漲。" },
  "More In The Next # Days To Advance": { 'zh-CN': "未来 # 天内再达成即可晋级", 'zh-TW': "未來 # 天內再達成即可晉級" },
  "Volume Discount (#+ Vials Per Peptide)": { 'zh-CN': "批量折扣（每种肽 #+ 瓶）", 'zh-TW': "批量折扣（每種肽 #+ 瓶）" },
  "Save even more, buy in bundles": { 'zh-CN': "买套装，省更多", 'zh-TW': "買套裝，省更多" },
  "Save This Month": { 'zh-CN': "本月节省", 'zh-TW': "本月節省" },
  "Month Streak!": { 'zh-CN': "个月连续达成！", 'zh-TW': "個月連續達成！" },

  // ── Common status / labels / empty states ────────────────
  "Are You Sure?": { 'zh-CN': "确定吗？", 'zh-TW': "確定嗎？" },
  "Contact Support": { 'zh-CN': "联系支持", 'zh-TW': "聯絡支援" },
  "Ask An Admin": { 'zh-CN': "咨询管理员", 'zh-TW': "諮詢管理員" },
  "Coverage:": { 'zh-CN': "覆盖范围：", 'zh-TW': "覆蓋範圍：" },
  "Configured": { 'zh-CN': "已配置", 'zh-TW': "已設定" },
  "Applied": { 'zh-CN': "已应用", 'zh-TW': "已套用" },
  "Added": { 'zh-CN': "已添加", 'zh-TW': "已新增" },
  "Selected": { 'zh-CN': "已选择", 'zh-TW': "已選擇" },
  "Uploaded": { 'zh-CN': "已上传", 'zh-TW': "已上傳" },
  "Unavailable": { 'zh-CN': "不可用", 'zh-TW': "不可用" },
  "Unlocked": { 'zh-CN': "已解锁", 'zh-TW': "已解鎖" },
  "Locked": { 'zh-CN': "已锁定", 'zh-TW': "已鎖定" },
  "Requested": { 'zh-CN': "已申请", 'zh-TW': "已申請" },
  "Require": { 'zh-CN': "需要", 'zh-TW': "需要" },
  "Requires An Account": { 'zh-CN': "需要账户", 'zh-TW': "需要帳戶" },
  "Role": { 'zh-CN': "角色", 'zh-TW': "角色" },
  "Reason": { 'zh-CN': "原因", 'zh-TW': "原因" },
  "Reason:": { 'zh-CN': "原因：", 'zh-TW': "原因：" },
  "Event": { 'zh-CN': "事件", 'zh-TW': "事件" },
  "Period": { 'zh-CN': "周期", 'zh-TW': "週期" },
  "Week": { 'zh-CN': "周", 'zh-TW': "週" },
  "Start": { 'zh-CN': "开始", 'zh-TW': "開始" },
  "End": { 'zh-CN': "结束", 'zh-TW': "結束" },
  "Need": { 'zh-CN': "需要", 'zh-TW': "需要" },
  "Sell": { 'zh-CN': "销售", 'zh-TW': "銷售" },
  "Generate": { 'zh-CN': "生成", 'zh-TW': "生成" },
  "Change": { 'zh-CN': "更改", 'zh-TW': "更改" },
  "Show All": { 'zh-CN': "显示全部", 'zh-TW': "顯示全部" },
  "Show All Time": { 'zh-CN': "显示全部时间", 'zh-TW': "顯示全部時間" },
  "Showing": { 'zh-CN': "正在显示", 'zh-TW': "正在顯示" },
  "Select A Researcher": { 'zh-CN': "选择一名研究员", 'zh-TW': "選擇一名研究員" },
  "Paste Or Click A Researcher Above": { 'zh-CN': "粘贴或点击上方的研究员", 'zh-TW': "貼上或點擊上方的研究員" },
  "Documents": { 'zh-CN': "文档", 'zh-TW': "文件" },
  "Documentation": { 'zh-CN': "文档", 'zh-TW': "文件" },
  "Grade": { 'zh-CN': "等级", 'zh-TW': "等級" },
  "Frequency:": { 'zh-CN': "频率：", 'zh-TW': "頻率：" },
  "Timezone": { 'zh-CN': "时区", 'zh-TW': "時區" },
  "Select Timezone": { 'zh-CN': "选择时区", 'zh-TW': "選擇時區" },
  "Select State": { 'zh-CN': "选择州", 'zh-TW': "選擇州" },
  "State *": { 'zh-CN': "州 *", 'zh-TW': "州 *" },
  "Zip Code": { 'zh-CN': "邮政编码", 'zh-TW': "郵遞區號" },
  "ZIP Code": { 'zh-CN': "邮政编码", 'zh-TW': "郵遞區號" },
  "Note (Optional)": { 'zh-CN': "备注（可选）", 'zh-TW': "備註（選填）" },
  "Note:": { 'zh-CN': "备注：", 'zh-TW': "備註：" },
  "Loading…": { 'zh-CN': "加载中…", 'zh-TW': "載入中…" },
  "Loading orders...": { 'zh-CN': "正在加载订单…", 'zh-TW': "正在載入訂單…" },
  "Loading agents...": { 'zh-CN': "正在加载代理…", 'zh-TW': "正在載入代理…" },
  "Loading Your Orders...": { 'zh-CN': "正在加载您的订单…", 'zh-TW': "正在載入您的訂單…" },
  "Loading Your Researchers...": { 'zh-CN': "正在加载您的研究员…", 'zh-TW': "正在載入您的研究員…" },
  "Loading Your Invitations...": { 'zh-CN': "正在加载您的邀请…", 'zh-TW': "正在載入您的邀請…" },
  "Loading Statements...": { 'zh-CN': "正在加载结算单…", 'zh-TW': "正在載入結算單…" },
  "Loading Sessions...": { 'zh-CN': "正在加载会话…", 'zh-TW': "正在載入工作階段…" },
  "Loading Preferences...": { 'zh-CN': "正在加载偏好设置…", 'zh-TW': "正在載入偏好設定…" },
  "Loading Referral Data...": { 'zh-CN': "正在加载推荐数据…", 'zh-TW': "正在載入推薦資料…" },
  "Loading Payment Proofs...": { 'zh-CN': "正在加载付款凭证…", 'zh-TW': "正在載入付款憑證…" },
  "Loading QR code...": { 'zh-CN': "正在加载二维码…", 'zh-TW': "正在載入 QR 碼…" },
  "Could Not Load Your Wallet": { 'zh-CN': "无法加载您的钱包", 'zh-TW': "無法載入您的錢包" },
  "Check Your Connection And Try Again.": { 'zh-CN': "请检查您的网络连接并重试。", 'zh-TW': "請檢查您的網路連線並重試。" },
  "Cannot Get Your Issue Resolved?": { 'zh-CN': "问题无法解决？", 'zh-TW': "問題無法解決？" },
  "Contact Your Agent For Assistance.": { 'zh-CN': "请联系您的代理寻求帮助。", 'zh-TW': "請聯絡您的代理尋求協助。" },
  "Please Check Back Soon Or Contact Your Agent For Assistance.": { 'zh-CN': "请稍后再来查看，或联系您的代理寻求帮助。", 'zh-TW': "請稍後再來查看，或聯絡您的代理尋求協助。" },
  "Is Temporarily Not Accepting New Orders.": { 'zh-CN': "暂时不接受新订单。", 'zh-TW': "暫時不接受新訂單。" },
  "Welcome To Pep Nation Lab!": { 'zh-CN': "欢迎来到 Pep Nation Lab！", 'zh-TW': "歡迎來到 Pep Nation Lab！" },
  "Your Researcher Account Is Active. Browse Our Catalog And Place Your First Order.": { 'zh-CN': "您的研究员账户已激活。浏览我们的目录并下您的第一笔订单吧。", 'zh-TW': "您的研究員帳戶已啟用。瀏覽我們的目錄並下您的第一筆訂單吧。" },

  // ── Reconstitution / supplies (checkout + product) ───────
  "Reconstitution Supplies": { 'zh-CN': "复溶用品", 'zh-TW': "複溶用品" },
  "Special Reconstitution Supplies": { 'zh-CN': "特殊复溶用品", 'zh-TW': "特殊複溶用品" },
  "Bacteriostatic Water For Reconstitution": { 'zh-CN': "用于复溶的抑菌水", 'zh-TW': "用於複溶的抑菌水" },
  "BAC Water Vial": { 'zh-CN': "抑菌水瓶", 'zh-TW': "抑菌水瓶" },
  "Acetic Acid Vial": { 'zh-CN': "乙酸瓶", 'zh-TW': "乙酸瓶" },
  "Acetic Acid Check": { 'zh-CN': "乙酸检查", 'zh-TW': "乙酸檢查" },
  "Wait — Does Your Lab Have BAC Water?": { 'zh-CN': "请稍等 — 您的实验室有抑菌水吗？", 'zh-TW': "請稍等 — 您的實驗室有抑菌水嗎？" },
  "My Lab Is Covered": { 'zh-CN': "我的实验室已备齐", 'zh-TW': "我的實驗室已備齊" },
  "BAC Water Covered -": { 'zh-CN': "抑菌水已备齐 -", 'zh-TW': "抑菌水已備齊 -" },
  "Of BAC Water To Cart": { 'zh-CN': "抑菌水加入购物车", 'zh-TW': "抑菌水加入購物車" },
  "Of BAC Water For Reconstitution.": { 'zh-CN': "抑菌水用于复溶。", 'zh-TW': "抑菌水用於複溶。" },
  "Of BAC Water — Suggested:": { 'zh-CN': "抑菌水 — 建议：", 'zh-TW': "抑菌水 — 建議：" },
  "Of Bacteriostatic Water.": { 'zh-CN': "抑菌水。", 'zh-TW': "抑菌水。" },
  "Of Bacteriostatic Water Added To Your Order.": { 'zh-CN': "抑菌水已加入您的订单。", 'zh-TW': "抑菌水已加入您的訂單。" },
  "Of Acetic Acid Added To Your Order.": { 'zh-CN': "乙酸已加入您的订单。", 'zh-TW': "乙酸已加入您的訂單。" },
  "Requiring BAC Water — Approximately": { 'zh-CN': "需要抑菌水 — 约", 'zh-TW': "需要抑菌水 — 約" },
  "Requiring Acetic Acid For Solubility. You Need Approximately": { 'zh-CN': "需要乙酸以助溶解。您大约需要", 'zh-TW': "需要乙酸以助溶解。您大約需要" },
  "With Acetic Acid # Instead Of BAC Water. Suggested:": { 'zh-CN': "使用乙酸 # 代替抑菌水。建议：", 'zh-TW': "使用乙酸 # 代替抑菌水。建議：" },
  "Total Based On Per-Vial Strength. We Recommend": { 'zh-CN': "基于每瓶剂量的总量。我们建议", 'zh-TW': "基於每瓶劑量的總量。我們建議" },
  ". Based On Per-Vial Strength, This Order Needs Approximately": { 'zh-CN': "。根据每瓶剂量，此订单大约需要", 'zh-TW': "。根據每瓶劑量，此訂單大約需要" },
  "In Your Order Reconstitute": { 'zh-CN': "在您的订单中复溶", 'zh-TW': "在您的訂單中複溶" },
  "Vials To Order": { 'zh-CN': "待订购瓶数", 'zh-TW': "待訂購瓶數" },
  "Needed (Rounded Up)": { 'zh-CN': "所需量（向上取整）", 'zh-TW': "所需量（向上取整）" },
  "Peptide Vial": { 'zh-CN': "肽瓶", 'zh-TW': "肽瓶" },
  "Research Vial": { 'zh-CN': "研究瓶", 'zh-TW': "研究瓶" },
  "Note: This peptide stack is not all inside one vial, it is individually packaged as the vials listed below.": { 'zh-CN': "注意：此肽组合并非全部装在一个瓶中，而是按下列各瓶单独包装。", 'zh-TW': "注意：此肽組合並非全部裝在一個瓶中，而是按下列各瓶單獨包裝。" },

  // ── Product cards / catalog helpers ──────────────────────
  "Compare Products": { 'zh-CN': "比较产品", 'zh-TW': "比較產品" },
  "Compare Pinned Products": { 'zh-CN': "比较已固定的产品", 'zh-TW': "比較已釘選的產品" },
  "Hide Identical Attributes": { 'zh-CN': "隐藏相同属性", 'zh-TW': "隱藏相同屬性" },
  "Highlight Differences": { 'zh-CN': "突出显示差异", 'zh-TW': "突出顯示差異" },
  "Close Comparison Matrix": { 'zh-CN': "关闭对比表", 'zh-TW': "關閉對比表" },
  "Select Product": { 'zh-CN': "选择产品", 'zh-TW': "選擇產品" },
  "Select Products (": { 'zh-CN': "选择产品（", 'zh-TW': "選擇產品（" },
  "New Stock Just Landed": { 'zh-CN': "新库存刚刚上架", 'zh-TW': "新庫存剛剛上架" },
  "Fresh Inventory Of Your Favorites Is In. Tap To Browse.": { 'zh-CN': "您喜爱的商品已有新库存。点击浏览。", 'zh-TW': "您喜愛的商品已有新庫存。點擊瀏覽。" },
  "Time To Refill": { 'zh-CN': "该补货了", 'zh-TW': "該補貨了" },
  "Refill Due": { 'zh-CN': "补货到期", 'zh-TW': "補貨到期" },
  "These Are Your Active Bundle Offers. Bundles Are Managed In The Bundle Manager.": { 'zh-CN': "这些是您正在生效的套装优惠。套装在“套装管理器”中管理。", 'zh-TW': "這些是您正在生效的套裝優惠。套裝在「套裝管理器」中管理。" },

  // ── Support / help ───────────────────────────────────────
  "Common Questions": { 'zh-CN': "常见问题", 'zh-TW': "常見問題" },
  "Search Frequently Asked Questions": { 'zh-CN': "搜索常见问题", 'zh-TW': "搜尋常見問題" },
  "Search Answers...": { 'zh-CN': "搜索答案…", 'zh-TW': "搜尋答案…" },
  "Jump To FAQ Category": { 'zh-CN': "跳转到常见问题类别", 'zh-TW': "跳至常見問題類別" },
  "Answers Below Or Start A Chat With Our Support Team.": { 'zh-CN': "查看下方答案，或与我们的支持团队开始聊天。", 'zh-TW': "查看下方答案，或與我們的支援團隊開始聊天。" },
  "Start A Direct Message With Our Support Team. We Will Reply In Your Messenger Inbox.": { 'zh-CN': "与我们的支持团队开始私信。我们将在您的消息收件箱中回复。", 'zh-TW': "與我們的支援團隊開始私訊。我們將在您的訊息收件匣中回覆。" },
  "Or Start A Support Chat Above.": { 'zh-CN': "或在上方开始支持聊天。", 'zh-TW': "或在上方開始支援聊天。" },
  "If The Support Chat Above Has Not Resolved Your Issue, Tap Below To Email Our Senior Support Team Directly. We Reply Within One Business Day.": { 'zh-CN': "如果上方的支持聊天未能解决您的问题，请点击下方直接给我们的高级支持团队发送电子邮件。我们将在一个工作日内回复。", 'zh-TW': "如果上方的支援聊天未能解決您的問題，請點擊下方直接給我們的高級支援團隊傳送電子郵件。我們將在一個工作日內回覆。" },
  "Tap To Escalate Via Email": { 'zh-CN': "点击通过电子邮件升级处理", 'zh-TW': "點擊透過電子郵件升級處理" },
  "Agent Help & Documentation": { 'zh-CN': "代理帮助与文档", 'zh-TW': "代理說明與文件" },
  "Everything An Agent Needs To Know To Run A Storefront. Read Top To Bottom The First Day, Then Come Back As A Reference.": { 'zh-CN': "代理经营店铺所需了解的一切。第一天从头到尾通读，之后可作为参考随时回看。", 'zh-TW': "代理經營店鋪所需了解的一切。第一天從頭到尾通讀，之後可作為參考隨時回看。" },
  "Everything across your storefront — orders, payments, researchers, commissions & more.": { 'zh-CN': "您店铺的方方面面 — 订单、付款、研究员、佣金等。", 'zh-TW': "您店鋪的方方面面 — 訂單、付款、研究員、佣金等。" },
  "Research Resources": { 'zh-CN': "研究资源", 'zh-TW': "研究資源" },
  "Review The Public Compliance Documents At Any Time.": { 'zh-CN': "您可随时查阅公开的合规文件。", 'zh-TW': "您可隨時查閱公開的合規文件。" },
};
