import { createServerClient } from '@supabase/ssr';
import { NextResponse, type NextRequest } from 'next/server';

// ─── SITE LOCKDOWN ──────────────────────────────────────────────────────────
// The site is locked. Only authenticated users may access any page.
// New account registration is disabled — /register always redirects to /login.
// The only public route is /login itself (plus static assets handled by matcher).
// ────────────────────────────────────────────────────────────────────────────

// Routes that are always public (no auth required)
const PUBLIC_ROUTES = [
  '/login',
  '/forgot-password',
  '/become-agent',
  '/about',
  '/terms',
  '/privacy',
  '/compliance',
  '/disclaimer',
  '/api/auth/resolve',
  '/api/auth/signout',
  // Liveness probe — must be reachable for monitoring.
  '/api/health',
  // Layer 1 (site_entry) disclaimer log is hit by anonymous visitors before login.
  // The route's own handler rejects anything other than site_entry from an
  // unauthenticated caller, so this is safe.
  '/api/disclaimer-log',
  // Storefront-scoped researcher signup (rate-limited inside the route).
  '/api/storefront/register',
  // Agent invitation redemption — the token in the URL is the credential.
  '/invite',
  '/api/agent-invitations/redeem',
  // Vercel cron entrypoints — authenticated via CRON_SECRET inside the route
  // using a constant-time compare, NOT via the session middleware.
  '/api/cron/invoices',
  '/api/cron/reminders',
  '/api/cron/sms-dispatch',
  '/api/cron/abandoned-cart-recovery',
  '/api/cron/apply-price-changes',
  '/api/cron/subscriptions-process',
  '/api/cron/referrals-fulfil',
  // PWA manifest — generated by app/manifest.ts and served at this path.
  '/manifest.webmanifest',
];

// Dynamic route check — agent storefronts are public
// e.g. /midway, /orlando-peps, etc. (but NOT /admin, /dashboard, /api, etc.)
function isPublicDynamicRoute(pathname: string): boolean {
  // Exclude known protected prefixes
  const protectedPrefixes = [
    '/admin', '/dashboard', '/api', '/orders', '/products',
    '/checkout', '/messages', '/register', '/login', '/forgot-password',
    '/become-agent', '/about', '/terms', '/privacy', '/compliance',
    '/disclaimer', '/shipping', '/invite',
  ];
  if (protectedPrefixes.some(p => pathname.startsWith(p))) return false;
  // A single-segment slug path (e.g. /midway) is a public storefront
  const segments = pathname.split('/').filter(Boolean);
  return segments.length === 1;
}

export default async function proxy(request: NextRequest) {
  // Pass through if Supabase env vars not configured yet (early deploy)
  if (!process.env.NEXT_PUBLIC_SUPABASE_URL || !process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY) {
    return NextResponse.next({ request });
  }

  const pathname = request.nextUrl.pathname;

  // Registration is permanently disabled — redirect to login
  if (pathname.startsWith('/register')) {
    const url = request.nextUrl.clone();
    url.pathname = '/login';
    url.search = '';
    return NextResponse.redirect(url);
  }

  // Allow public routes through immediately
  if (PUBLIC_ROUTES.some(route => pathname === route || pathname.startsWith(route + '/'))) {
    return NextResponse.next({ request });
  }

  // Allow public agent storefronts through
  if (isPublicDynamicRoute(pathname)) {
    return NextResponse.next({ request });
  }

  // Allow Next internals
  if (
    pathname.startsWith('/_next') ||
    pathname.startsWith('/favicon') ||
    pathname === '/robots.txt' ||
    pathname === '/sitemap.xml' ||
    pathname.match(/\.(png|jpg|jpeg|svg|webp|ico|gif|css|js|woff|woff2|map)$/)
  ) {
    return NextResponse.next({ request });
  }

  // ─── Authenticated paths ──────────────────────────────────────────────────
  let response = NextResponse.next({ request });

  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll() {
          return request.cookies.getAll();
        },
        setAll(cookiesToSet) {
          cookiesToSet.forEach(({ name, value, options }) => {
            request.cookies.set({ name, value, ...options });
          });
          response = NextResponse.next({ request });
          cookiesToSet.forEach(({ name, value, options }) => {
            response.cookies.set({ name, value, ...options });
          });
        },
      },
    },
  );

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    if (pathname.startsWith('/api/')) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }
    const url = request.nextUrl.clone();
    url.pathname = '/login';
    url.searchParams.set('redirect', pathname);
    return NextResponse.redirect(url);
  }

  // Check the user's is_active flag — deactivated accounts get signed out.
  const { data: profile } = await supabase
    .from('profiles')
    .select('is_active, role')
    .eq('id', user.id)
    .maybeSingle();

  if (profile && profile.is_active === false) {
    await supabase.auth.signOut();
    if (pathname.startsWith('/api/')) {
      return NextResponse.json({ error: 'Account disabled' }, { status: 401 });
    }
    const url = request.nextUrl.clone();
    url.pathname = '/login';
    url.searchParams.set('error', 'account_disabled');
    return NextResponse.redirect(url);
  }

  // Already-logged-in users land on /login → bounce to their dashboard
  if (pathname === '/login') {
    const url = request.nextUrl.clone();
    url.pathname = profile?.role === 'admin' ? '/admin' : '/dashboard';
    return NextResponse.redirect(url);
  }

  // ─── MFA Enforcement (admin + super_agent) ────────────────────────────────
  // Roles that must have a verified TOTP factor before they can touch the
  // rest of the platform. The enrollment UI lives at /account/security and
  // is whitelisted below so the user can actually enroll.
  const mfaRequiredRoles = new Set(['admin', 'super_agent']);
  if (profile?.role && mfaRequiredRoles.has(profile.role)) {
    const isMfaExempt =
      pathname === '/account/security' ||
      pathname.startsWith('/account/security/') ||
      pathname.startsWith('/api/auth/') ||
      pathname === '/api/health';

    if (!isMfaExempt) {
      // getAuthenticatorAssuranceLevel returns { currentLevel, nextLevel }.
      // nextLevel === 'aal2' when the user has at least one verified factor;
      // currentLevel === 'aal2' when the current session was elevated. We
      // require nextLevel to be 'aal2' as the minimum bar — i.e. the user
      // has a factor enrolled at all.
      const { data: aal } =
        await supabase.auth.mfa.getAuthenticatorAssuranceLevel();
      const hasVerifiedFactor = aal?.nextLevel === 'aal2';

      if (!hasVerifiedFactor) {
        if (pathname.startsWith('/api/')) {
          return NextResponse.json(
            { error: 'MFA enrollment required.' },
            { status: 403 }
          );
        }
        const url = request.nextUrl.clone();
        url.pathname = '/account/security';
        url.search = '?reason=mfa_required';
        return NextResponse.redirect(url);
      }
    }
  }

  return response;
}

export const config = {
  matcher: [
    /*
     * Match all request paths except for the ones starting with:
     * - _next/static (static files)
     * - _next/image (image optimization files)
     * - favicon.ico (favicon file)
     * - public files (images, fonts, etc.)
     */
    '/((?!_next/static|_next/image|favicon.ico|logo.*|.*\\.(?:png|jpg|jpeg|gif|webp|svg|ico|woff|woff2|css|js|map)$).*)',
  ],
};
