/**
 * AI tutor for the Peptide 101 course. A signed-in learner can ask any
 * question about the module they just finished. Answers are generated by
 * Gemini with strict research-education guardrails: never medical advice,
 * never human dosing/protocols, always framed as research. The model also
 * proposes 3 natural follow-up questions to keep the conversation going.
 *   POST { question, module } -> { answer, followups: string[] }
 */
import { NextResponse, type NextRequest } from 'next/server';
import { GoogleGenAI } from '@google/genai';
import { createClient } from '@/lib/supabase/server';
import { assertSameOrigin } from '@/lib/csrf';
import { rateLimit, getClientIp } from '@/lib/rate-limit';

export const dynamic = 'force-dynamic';

export async function POST(req: NextRequest) {
  const csrf = assertSameOrigin(req);
  if (csrf) return csrf;

  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) {
    return NextResponse.json({ error: 'Please Sign In To Ask The AI Tutor.' }, { status: 401 });
  }

  const limited = await rateLimit({
    key: 'p101_ask',
    limit: 12,
    windowSeconds: 60,
    identifier: user.id || getClientIp(req),
  });
  if (!limited.allowed) {
    return NextResponse.json(
      { error: 'You Are Asking Quickly - Give It A Moment And Try Again.' },
      { status: 429 },
    );
  }

  let body: { question?: unknown; module?: unknown };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 });
  }

  const question = typeof body.question === 'string' ? body.question.trim().slice(0, 500) : '';
  const moduleTopic =
    typeof body.module === 'string' ? body.module.trim().slice(0, 120) : 'peptide basics';
  if (question.length < 3) {
    return NextResponse.json({ error: 'Please Type A Longer Question.' }, { status: 400 });
  }

  if (!process.env.GEMINI_API_KEY) {
    return NextResponse.json(
      { error: 'The AI Tutor Is Not Available Right Now.' },
      { status: 501 },
    );
  }

  const prompt = `You are the friendly AI tutor for "Peptide 101," a beginner research-education course on PepNationLab. A learner just finished the module about: ${moduleTopic}.

They asked: "${question}"

Answer in plain, beginner-friendly language. Explain any jargon you use. Be accurate and genuinely educational. Keep it concise - about 2 to 3 short paragraphs or a short bullet list, under roughly 180 words. You may use simple markdown (bold, bullet points).

Strict rules you must always follow:
- This is research and education only. Never give medical advice. Never tell the user to take, dose, inject, buy, or use anything. Never provide human dosing amounts, schedules, or protocols for personal use. If asked for any of those, briefly say you can only discuss peptides as research education and suggest speaking with a qualified professional, then offer a general educational point instead.
- Always frame statements as what researchers study, not what the user should do.
- If the question is off-topic or not about peptides or this course, gently steer back to the course material.
- Do not mention that you are an AI or add boilerplate disclaimers. Just answer helpfully within these rules.

After your answer, output one final line in exactly this format:
FOLLOWUPS: <question 1> | <question 2> | <question 3>
Those are three short, natural follow-up questions (each under about 12 words) a curious beginner might ask next about this topic. No numbering, no extra words, just the three questions separated by the pipe character.`;

  try {
    const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });
    let answer = (response.text || '').trim();
    if (!answer) {
      return NextResponse.json(
        { error: 'The Tutor Could Not Answer That. Try Rewording Your Question.' },
        { status: 502 },
      );
    }

    // Split off the FOLLOWUPS line if present.
    let followups: string[] = [];
    const idx = answer.search(/FOLLOWUPS\s*:/i);
    if (idx >= 0) {
      const tail = answer.slice(idx).replace(/^[\s\S]*?FOLLOWUPS\s*:/i, '');
      followups = tail
        .split('|')
        .map((s) => s.replace(/^[\d.)\-\s]+/, '').replace(/[\r\n]+/g, ' ').trim())
        .filter((s) => s.length > 0 && s.length <= 120)
        .slice(0, 3);
      answer = answer.slice(0, idx).trim();
    }

    return NextResponse.json({ answer, followups });
  } catch (err) {
    console.error('peptide-101 ask error:', err);
    return NextResponse.json({ error: 'Something Went Wrong. Please Try Again.' }, { status: 500 });
  }
}
