#!/usr/bin/env node
/**
 * split-cities.mjs
 * Reads lib/cities/cities-data.ts, extracts all City objects grouped by stateSlug,
 * writes lib/cities/data/<stateSlug>.ts for each state, then rewrites
 * lib/cities/cities-data.ts as a thin barrel that imports and concatenates them.
 *
 * Run from repo root: node split-cities.mjs
 */
import fs from 'fs';
import path from 'path';

const SRC = 'lib/cities/cities-data.ts';
const DATA_DIR = 'lib/cities/data';

// ── Read source ──────────────────────────────────────────────────────────────
const raw = fs.readFileSync(SRC, 'utf8');

// Extract the interface + type block (everything before `export const CITIES`)
const interfaceMatch = raw.match(/^([\s\S]*?)export const CITIES/m);
const headerBlock = interfaceMatch ? interfaceMatch[1] : '';

// Extract the CITIES array body: everything between `= [` and the final `];`
const arrayMatch = raw.match(/export const CITIES: City\[\] = \[([\s\S]*?)\];\s*(?:\/\/[^\n]*)?\s*(?:export function|$)/m);
if (!arrayMatch) {
  console.error('Could not find CITIES array in', SRC);
  process.exit(1);
}
const arrayBody = arrayMatch[1];

// Extract trailing export functions (everything after the closing `];`)
const trailingMatch = raw.match(/\];\s*([\s\S]*?)$/m);
const trailingFunctions = trailingMatch ? trailingMatch[1].trim() : '';

// ── Parse individual City objects ────────────────────────────────────────────
// Strategy: split on `},` boundaries while tracking brace depth to handle nested objects
function splitCityObjects(body) {
  const objs = [];
  let depth = 0;
  let start = -1;
  for (let i = 0; i < body.length; i++) {
    const ch = body[i];
    if (ch === '{') {
      if (depth === 0) start = i;
      depth++;
    } else if (ch === '}') {
      depth--;
      if (depth === 0 && start !== -1) {
        objs.push(body.slice(start, i + 1).trim());
        start = -1;
      }
    }
  }
  return objs;
}

const cityObjects = splitCityObjects(arrayBody);
console.log(`Found ${cityObjects.length} city objects`);

// ── Group by stateSlug ────────────────────────────────────────────────────────
const byState = new Map(); // stateSlug -> City[]
const stateOrder = []; // preserve original order of first appearance

for (const obj of cityObjects) {
  const m = obj.match(/stateSlug:\s*['"]([^'"]+)['"]/);
  if (!m) { console.warn('No stateSlug found in:', obj.slice(0, 80)); continue; }
  const slug = m[1];
  if (!byState.has(slug)) { byState.set(slug, []); stateOrder.push(slug); }
  byState.get(slug).push(obj);
}

console.log(`States found: ${stateOrder.length}`);

// ── Ensure output directory ───────────────────────────────────────────────────
fs.mkdirSync(DATA_DIR, { recursive: true });

// ── Write per-state files ─────────────────────────────────────────────────────
for (const stateSlug of stateOrder) {
  const cities = byState.get(stateSlug);
  const stateName = cities[0].match(/state:\s*['"]([^'"]+)['"]/)?.[1] ?? stateSlug;
  const content = `import type { City } from '../cities-data';\n\n` +
    `// ${stateName} — ${cities.length} cities\n` +
    `const CITIES_${stateSlug.toUpperCase().replace(/-/g, '_')}: City[] = [\n  ` +
    cities.join(',\n  ') +
    `,\n];\n\nexport default CITIES_${stateSlug.toUpperCase().replace(/-/g, '_')};\n`;
  
  const outPath = path.join(DATA_DIR, `${stateSlug}.ts`);
  fs.writeFileSync(outPath, content, 'utf8');
  console.log(`  Wrote ${outPath} (${cities.length} cities)`);
}

// ── Rewrite barrel cities-data.ts ────────────────────────────────────────────
const imports = stateOrder
  .map(s => `import CITIES_${s.toUpperCase().replace(/-/g, '_')} from './data/${s}';`)
  .join('\n');

const concat = stateOrder
  .map(s => `  ...CITIES_${s.toUpperCase().replace(/-/g, '_')}`)
  .join(',\n');

const barrel = `${headerBlock}// Auto-generated barrel — do NOT edit this file by hand.
// Add cities by editing the relevant lib/cities/data/<state>.ts file.
// Re-run scripts/split-cities.mjs if you need to restructure.

${imports}

export const CITIES: City[] = [
${concat},
];

${trailingFunctions}
`.replace(/\n{3,}/g, '\n\n'); // collapse excess blank lines

fs.writeFileSync(SRC, barrel, 'utf8');
console.log(`\nRewritten ${SRC} as a ${stateOrder.length}-state barrel`);
console.log('Done. Run: npx tsc --noEmit');
