/**
 * cities-data.ts
 * Master list of US cities for local SEO landing page generation.
 * Tier 1 = highest wealth/population priority (Beverly Hills, Scottsdale, etc.)
 * Tier 2 = strong metro suburbs with disposable income
 * Tier 3 = mid-size cities with measurable peptide-related search volume
 */

export interface City {
  name: string;
  slug: string;           // URL slug, e.g. "oak-lawn"
  state: string;          // Full state name, e.g. "Illinois"
  stateSlug: string;      // URL-safe state slug, e.g. "illinois"
  stateAbbr: string;      // Two-letter state abbreviation, e.g. "IL"
  population: number;
  medianIncome: number;   // Approximate median household income (USD)
  tier: 1 | 2 | 3;
  region?: string;        // Optional regional label, e.g. "Chicagoland area"
  county?: string;        // County name WITHOUT the word "County", e.g. "Cook"
  zips?: string[];        // Representative ZIP codes for the city
  localBlurb?: string;    // Unique city-specific copy rendered on the landing page
}

// Auto-generated barrel — do NOT edit this file by hand EXCEPT to register a new
// per-state file (add one import + one spread). Add cities by editing the
// relevant lib/cities/data/<state>.ts file. Re-run scripts/split-cities.mjs if
// you need to restructure.

import CITIES_CALIFORNIA from './data/california';
import CITIES_ARIZONA from './data/arizona';
import CITIES_FLORIDA from './data/florida';
import CITIES_TEXAS from './data/texas';
import CITIES_ILLINOIS from './data/illinois';
import CITIES_NEW_YORK from './data/new-york';
import CITIES_NEW_JERSEY from './data/new-jersey';
import CITIES_GEORGIA from './data/georgia';
import CITIES_WASHINGTON from './data/washington';
import CITIES_COLORADO from './data/colorado';
import CITIES_NEVADA from './data/nevada';
import CITIES_CONNECTICUT from './data/connecticut';
import CITIES_MASSACHUSETTS from './data/massachusetts';
import CITIES_VIRGINIA from './data/virginia';
import CITIES_MARYLAND from './data/maryland';
import CITIES_PENNSYLVANIA from './data/pennsylvania';
import CITIES_OHIO from './data/ohio';
import CITIES_MICHIGAN from './data/michigan';
import CITIES_MINNESOTA from './data/minnesota';
import CITIES_NORTH_CAROLINA from './data/north-carolina';
import CITIES_TENNESSEE from './data/tennessee';
import CITIES_KANSAS from './data/kansas';
import CITIES_MISSOURI from './data/missouri';
import CITIES_INDIANA from './data/indiana';
import CITIES_UTAH from './data/utah';
import CITIES_OREGON from './data/oregon';
import CITIES_WISCONSIN from './data/wisconsin';
import CITIES_SOUTH_CAROLINA from './data/south-carolina';
import CITIES_LOUISIANA from './data/louisiana';
import CITIES_ALABAMA from './data/alabama';
import CITIES_NEBRASKA from './data/nebraska';
import CITIES_IOWA from './data/iowa';
import CITIES_OKLAHOMA from './data/oklahoma';
import CITIES_ARKANSAS from './data/arkansas';
import CITIES_NEW_MEXICO from './data/new-mexico';
import CITIES_HAWAII from './data/hawaii';
import CITIES_ALASKA from './data/alaska';
import CITIES_DELAWARE from './data/delaware';
import CITIES_IDAHO from './data/idaho';
import CITIES_KENTUCKY from './data/kentucky';
import CITIES_MAINE from './data/maine';
import CITIES_MISSISSIPPI from './data/mississippi';
import CITIES_MONTANA from './data/montana';
import CITIES_NEW_HAMPSHIRE from './data/new-hampshire';
import CITIES_NORTH_DAKOTA from './data/north-dakota';
import CITIES_RHODE_ISLAND from './data/rhode-island';
import CITIES_SOUTH_DAKOTA from './data/south-dakota';
import CITIES_VERMONT from './data/vermont';
import CITIES_WEST_VIRGINIA from './data/west-virginia';
import CITIES_WYOMING from './data/wyoming';

export const CITIES: City[] = [
  ...CITIES_CALIFORNIA,
  ...CITIES_ARIZONA,
  ...CITIES_FLORIDA,
  ...CITIES_TEXAS,
  ...CITIES_ILLINOIS,
  ...CITIES_NEW_YORK,
  ...CITIES_NEW_JERSEY,
  ...CITIES_GEORGIA,
  ...CITIES_WASHINGTON,
  ...CITIES_COLORADO,
  ...CITIES_NEVADA,
  ...CITIES_CONNECTICUT,
  ...CITIES_MASSACHUSETTS,
  ...CITIES_VIRGINIA,
  ...CITIES_MARYLAND,
  ...CITIES_PENNSYLVANIA,
  ...CITIES_OHIO,
  ...CITIES_MICHIGAN,
  ...CITIES_MINNESOTA,
  ...CITIES_NORTH_CAROLINA,
  ...CITIES_TENNESSEE,
  ...CITIES_KANSAS,
  ...CITIES_MISSOURI,
  ...CITIES_INDIANA,
  ...CITIES_UTAH,
  ...CITIES_OREGON,
  ...CITIES_WISCONSIN,
  ...CITIES_SOUTH_CAROLINA,
  ...CITIES_LOUISIANA,
  ...CITIES_ALABAMA,
  ...CITIES_NEBRASKA,
  ...CITIES_IOWA,
  ...CITIES_OKLAHOMA,
  ...CITIES_ARKANSAS,
  ...CITIES_NEW_MEXICO,
  ...CITIES_HAWAII,
  ...CITIES_ALASKA,
  ...CITIES_DELAWARE,
  ...CITIES_IDAHO,
  ...CITIES_KENTUCKY,
  ...CITIES_MAINE,
  ...CITIES_MISSISSIPPI,
  ...CITIES_MONTANA,
  ...CITIES_NEW_HAMPSHIRE,
  ...CITIES_NORTH_DAKOTA,
  ...CITIES_RHODE_ISLAND,
  ...CITIES_SOUTH_DAKOTA,
  ...CITIES_VERMONT,
  ...CITIES_WEST_VIRGINIA,
  ...CITIES_WYOMING,
];

// ─── Content versioning ───────────────────────────────────────────────────────
/**
 * Bump this date ONLY when city page content materially changes (copy, FAQs,
 * schema, layout). It feeds sitemap <lastmod> and schema dateModified. Do NOT
 * use `new Date()` for lastmod - stamping every build teaches crawlers to
 * ignore the signal.
 */
export const CITY_CONTENT_UPDATED = new Date('2026-07-11');

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** Returns all unique state slugs present in the city data */
export function getStatesSlugs(): string[] {
  return [...new Set(CITIES.map((c) => c.stateSlug))].sort();
}

/** Returns all cities for a given state slug */
export function getCitiesByState(stateSlug: string): City[] {
  return CITIES.filter((c) => c.stateSlug === stateSlug);
}

/** Returns a single city by state + city slug pair */
export function getCity(stateSlug: string, citySlug: string): City | undefined {
  return CITIES.find((c) => c.stateSlug === stateSlug && c.slug === citySlug);
}

/** Returns all Tier 1 cities sorted by median income descending */
export function getTier1Cities(): City[] {
  return CITIES.filter((c) => c.tier === 1).sort((a, b) => b.medianIncome - a.medianIncome);
}

/** Returns cities grouped by state slug */
export function getCitiesGroupedByState(): Record<string, City[]> {
  return CITIES.reduce<Record<string, City[]>>((acc, city) => {
    if (!acc[city.stateSlug]) acc[city.stateSlug] = [];
    acc[city.stateSlug].push(city);
    return acc;
  }, {});
}

/** State display name from slug */
export function getStateName(stateSlug: string): string {
  const city = CITIES.find((c) => c.stateSlug === stateSlug);
  return city?.state ?? stateSlug;
}
