import { NextResponse } from 'next/server';
import { createAdminClient } from '@/lib/supabase/server';
import { requireAgent } from '@/lib/admin-auth';
import { previousCompletedWeekStartCst, chicagoMidnightIso } from '@/lib/time-cst';
import { shortOrderId } from '@/lib/push-enqueue';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

function addDays(dateStr: string, days: number): string {
  const d = new Date(`${dateStr}T00:00:00Z`);
  d.setUTCDate(d.getUTCDate() + days);
  return d.toISOString().slice(0, 10);
}

const ACTIVE_ORDER_STATUSES = ['approved_ship', 'approved_pickup', 'in_fulfillment', 'shipped', 'delivered'];

/**
 * GET /api/agent/downline-balances
 *
 * Live, mid-week running totals for every direct downline of the caller:
 * open (unpaid) invoice balance, this week's order volume, and - for
 * prepaid downlines - orders still awaiting the upline's payment
 * confirmation. This is a read-only snapshot for the upline's dashboard;
 * weekly_statements / agent_invoices generated by the Monday cron remain
 * the authoritative bill.
 */
export async function GET() {
  const gate = await requireAgent();
  if (!gate.ok) return gate.response;

  const svc = createAdminClient();
  const callerId = gate.user.id;

  const { data: downlines, error: downlineErr } = await svc
    .from('profiles')
    .select('id, full_name, account_type, prepaid_balance, credit_used, credit_limit')
    .eq('parent_agent_id', callerId)
    .eq('role', 'agent')
    .limit(200);

  if (downlineErr) {
    console.error('[downline-balances] downline fetch failed:', downlineErr.message);
    return NextResponse.json({ error: 'Failed To Load Downline Balances.' }, { status: 500 });
  }

  const lastCompletedWeekStart = previousCompletedWeekStartCst(new Date());
  const currentWeekStart = addDays(lastCompletedWeekStart, 7);
  const weekEndsAtIso = chicagoMidnightIso(addDays(currentWeekStart, 7));

  const downlineRows = downlines ?? [];

  if (downlineRows.length === 0) {
    return NextResponse.json({ weekStart: currentWeekStart, weekEndsAtIso, downlines: [] });
  }

  const ids = downlineRows.map((d) => d.id);

  const [{ data: openInvoices }, { data: currentWeekOrders }] = await Promise.all([
    svc
      .from('agent_invoices')
      .select('agent_id, total_owed, week_start')
      .eq('super_agent_id', callerId)
      .eq('status', 'open')
      .in('agent_id', ids),
    svc
      .from('orders')
      .select('agent_id, total')
      .in('agent_id', ids)
      .gte('agent_approved_at', chicagoMidnightIso(currentWeekStart))
      .in('status', ACTIVE_ORDER_STATUSES)
      .limit(2000),
  ]);

  const invoiceByAgent = new Map<string, { total: number; count: number; oldest: string | null }>();
  for (const inv of openInvoices ?? []) {
    const cur = invoiceByAgent.get(inv.agent_id) ?? { total: 0, count: 0, oldest: null as string | null };
    cur.total += Number(inv.total_owed) || 0;
    cur.count += 1;
    if (!cur.oldest || inv.week_start < cur.oldest) cur.oldest = inv.week_start;
    invoiceByAgent.set(inv.agent_id, cur);
  }

  const orderByAgent = new Map<string, { count: number; total: number }>();
  for (const o of currentWeekOrders ?? []) {
    const cur = orderByAgent.get(o.agent_id) ?? { count: 0, total: 0 };
    cur.count += 1;
    cur.total += Number(o.total) || 0;
    orderByAgent.set(o.agent_id, cur);
  }

  const prepaidIds = downlineRows.filter((d) => d.account_type === 'prepaid').map((d) => d.id);
  const unconfirmedByAgent = new Map<
    string,
    Array<{ orderId: string; shortId: string; total: number; createdAt: string }>
  >();

  if (prepaidIds.length > 0) {
    const thirtyDaysAgoIso = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString();
    const { data: unconfirmed } = await svc
      .from('orders')
      .select('id, agent_id, total, created_at')
      .in('agent_id', prepaidIds)
      .is('payment_confirmed_at', null)
      .in('status', ACTIVE_ORDER_STATUSES)
      .gte('created_at', thirtyDaysAgoIso)
      .order('created_at', { ascending: false })
      .limit(300);

    for (const o of unconfirmed ?? []) {
      const list = unconfirmedByAgent.get(o.agent_id) ?? [];
      if (list.length < 25) {
        list.push({
          orderId: o.id,
          shortId: shortOrderId(o.id),
          total: Number(o.total) || 0,
          createdAt: o.created_at,
        });
      }
      unconfirmedByAgent.set(o.agent_id, list);
    }
  }

  const result = downlineRows.map((d) => {
    const inv = invoiceByAgent.get(d.id);
    const ord = orderByAgent.get(d.id);
    return {
      id: d.id,
      fullName: d.full_name,
      accountType: d.account_type,
      prepaidBalance: Number(d.prepaid_balance) || 0,
      creditUsed: Number(d.credit_used) || 0,
      creditLimit: Number(d.credit_limit) || 0,
      openInvoiceTotal: inv ? inv.total : 0,
      openInvoiceCount: inv ? inv.count : 0,
      oldestOpenWeekStart: inv ? inv.oldest : null,
      currentWeekOrderCount: ord ? ord.count : 0,
      currentWeekOrderTotal: ord ? ord.total : 0,
      unconfirmedPayments: unconfirmedByAgent.get(d.id) ?? [],
    };
  });

  return NextResponse.json({ weekStart: currentWeekStart, weekEndsAtIso, downlines: result });
}
