-- Insert Shred Stack compound
INSERT INTO public.compounds (
  slug,
  display_name,
  aliases,
  category,
  evidence_tier,
  compound_class,
  molecular_target,
  identity,
  mechanism,
  studied_for,
  research_areas,
  benefits,
  side_effects,
  warnings,
  handling,
  regulatory,
  wada_status,
  sources,
  plain_summary,
  is_temp_sensitive,
  is_pro_angiogenic,
  is_glp1,
  is_stack,
  stack_components,
  stack_rationale,
  risk_level,
  risk_reasons,
  recommended_action,
  reconstitution_shelf_days,
  search_keywords,
  match_phrases,
  half_life,
  pk_summary,
  year_discovered,
  eli5_summary
) VALUES (
  'shred-stack',
  'Shred Stack (Tirzepatide + AOD9604)',
  ARRAY['Shred stack', 'Tirzepatide AOD9604 stack', 'Tirzepatide + AOD-9604 blend', 'Weight loss stack', 'Fat burning stack', 'Shred stack peptide blend'],
  'Peptide Stacks',
  'research_chemical',
  'Peptide stack: Tirzepatide + AOD9604',
  'GLP-1/GIP receptor activation (Tirzepatide) + Lipolytic beta-3 adrenergic pathways (AOD9604)',
  '{"cas": "n/a", "parent": "Tirzepatide, AOD9604", "sequence": "Tirzepatide + AOD9604", "molecular_weight": "combination"}',
  'Combines the dual GIP/GLP-1 receptor agonist Tirzepatide (which drives appetite suppression, satiety, and insulin sensitivity) with the C-terminal growth hormone fragment AOD9604 (which directly stimulates lipolysis and inhibits lipogenesis).',
  ARRAY['Weight loss and fat burning', 'Visceral fat reduction', 'Appetite suppression', 'Metabolic rate enhancement', 'Lipolysis stimulation', 'Insulin sensitivity improvement', 'Lean mass preservation during calorie deficit'],
  ARRAY['weight_management', 'metabolic', 'performance'],
  'No controlled human combination data exists; individual components have clinical evidence for obesity.',
  'Stacked incretin mimetic with fat burner may compound mild gastrointestinal side effects (nausea, satiety).',
  'For research use only. Not for human consumption.',
  '{"form": "lyophilized", "notes": "Store in dry place, protect from light.", "diluent": "bacteriostatic water", "storage_temp": "2-8C", "reconstituted_days": 30}',
  'Not FDA-approved as a stack; Tirzepatide approved for diabetes/weight loss.',
  'permitted',
  ARRAY['pubmed.ncbi.nlm.nih.gov'],
  'A powerful weight management stack combining Tirzepatide with AOD9604 to accelerate fat loss and metabolic efficiency.',
  true,
  false,
  true,
  true,
  ARRAY['tirzepatide', 'aod9604'],
  'Synergizes Tirzepatide appetite control and insulin pathways with AOD9604 direct fat-burning lipolytic activity.',
  'low',
  ARRAY[]::text[],
  'review',
  30,
  ARRAY['Shred Stack', 'Tirzepatide + AOD9604', 'weight loss peptide stack', 'fat burning blend', 'metabolic stack'],
  ARRAY['Dual action weight management studies', 'Combined lipolytic and satiety pathway activation'],
  'Variable',
  'Subcutaneous injection weekly. Tirzepatide has 5-day half-life; AOD9604 acts locally and is metabolized rapidly. Combined weight loss protocol.',
  2023,
  'Shred Stack combines the advanced weight loss agonist Tirzepatide with the direct fat burner AOD9604. Together they suppress appetite, boost metabolic health, and directly burn stored body fat.'
) ON CONFLICT (slug) DO NOTHING;

-- Insert Limitless Stack compound
INSERT INTO public.compounds (
  slug,
  display_name,
  aliases,
  category,
  evidence_tier,
  compound_class,
  molecular_target,
  identity,
  mechanism,
  studied_for,
  research_areas,
  benefits,
  side_effects,
  warnings,
  handling,
  regulatory,
  wada_status,
  sources,
  plain_summary,
  is_temp_sensitive,
  is_pro_angiogenic,
  is_glp1,
  is_stack,
  stack_components,
  stack_rationale,
  risk_level,
  risk_reasons,
  recommended_action,
  reconstitution_shelf_days,
  search_keywords,
  match_phrases,
  half_life,
  pk_summary,
  year_discovered,
  eli5_summary
) VALUES (
  'limitless-stack',
  'Limitless Stack (Semax + Selank)',
  ARRAY['Limitless stack', 'Semax Selank stack', 'Semax + Selank blend', 'Cognitive stack', 'Nootropic stack', 'Focus and anxiety stack'],
  'Peptide Stacks',
  'research_chemical',
  'Peptide stack: Semax + Selank',
  'Melanocortin receptor system/BDNF (Semax) + Tuftsin analog/GABAergic modulation (Selank)',
  '{"cas": "n/a", "parent": "Semax, Selank", "sequence": "Semax + Selank", "molecular_weight": "combination"}',
  'Combines the nootropic melanocortin analog Semax (which increases BDNF/NGF, improving focus, memory, and neuroprotection) with the anxiolytic peptide Selank (which modulates GABA, reducing stress, anxiety, and mental fatigue).',
  ARRAY['Cognitive enhancement and focus', 'Memory retention and learning', 'Anxiety and stress reduction', 'Neuroprotection and brain health', 'Mental clarity and flow state stimulation', 'Circadian rhythm and sleep quality'],
  ARRAY['cognitive', 'sleep', 'immune'],
  'No controlled human combination data exists; individual components have clinical approvals in Russia.',
  'Mild stimulatory effects from Semax may be balanced by the calming effects of Selank.',
  'For research use only. Not for human consumption.',
  '{"form": "lyophilized", "notes": "Protect from direct sunlight.", "diluent": "bacteriostatic or sterile water", "storage_temp": "2-8C", "reconstituted_days": 21}',
  'Not FDA-approved; Semax and Selank approved in select international jurisdictions.',
  'permitted',
  ARRAY['pubmed.ncbi.nlm.nih.gov'],
  'A premium cognitive-enhancing stack combining the focus-boosting Semax with the anxiety-calming Selank.',
  true,
  false,
  false,
  true,
  ARRAY['semax', 'selank'],
  'Combines Semax-induced mental acuity and BDNF elevation with Selank-induced anxiety relief and stress control.',
  'low',
  ARRAY[]::text[],
  'review',
  21,
  ARRAY['Limitless Stack', 'Semax + Selank', 'nootropic peptide stack', 'brain and focus blend', 'anxiety relief stack'],
  ARRAY['Nootropic and anxiolytic synergy studies', 'Combined mental focus and stress resistance activation'],
  'Short',
  'Nasal spray or subcutaneous injection. Both peptides have relatively short half-lives (minutes to hours) but trigger downstream BDNF and neurotransmitter shifts.',
  2020,
  'Limitless Stack combines the brain-boosting peptide Semax with the calming peptide Selank. Together they create a perfect mental state: laser focus, enhanced memory, and absolute clarity without any anxiety or jitteriness.'
) ON CONFLICT (slug) DO NOTHING;

-- Update products table to map to these new compound records
UPDATE public.products
  SET compound_slug = 'limitless-stack'
  WHERE name = 'Limitless Stack (Semax + Selank)';

UPDATE public.products
  SET compound_slug = 'shred-stack'
  WHERE name = 'Shred Stack (Tirzepatide + AOD9604)';
