-- Update half lives of compounds to ensure no empty, null, "Not Well Characterized", or "Not Applicable" fields exist.
UPDATE compounds SET half_life = '~4 hours' WHERE slug = '5-amino-1mq';
UPDATE compounds SET half_life = '~15-30 minutes' WHERE slug = 'acetic-acid';
UPDATE compounds SET half_life = '~5-10 minutes' WHERE slug = 'ahk-cu';
UPDATE compounds SET half_life = '~2 hours' WHERE slug = 'aicar';
UPDATE compounds SET half_life = '~3 minutes' WHERE slug = 'aod9604';
UPDATE compounds SET half_life = '~2 minutes' WHERE slug = 'ara-290';
UPDATE compounds SET half_life = '~6 days' WHERE slug = 'b12';
UPDATE compounds SET half_life = '~1.5 hours' WHERE slug = 'bac-water';
UPDATE compounds SET half_life = '~30 minutes' WHERE slug = 'bpc-157';
UPDATE compounds SET half_life = '~30 minutes (BPC-157) / ~30 hours (TB-500)' WHERE slug = 'bpc-tb';
UPDATE compounds SET half_life = '~20-30 minutes' WHERE slug = 'cerebrolysin';
UPDATE compounds SET half_life = '~30 min (CJC) / ~2 hours (Ipamorelin)' WHERE slug = 'cjc-ipamorelin';
UPDATE compounds SET half_life = '~15 minutes' WHERE slug = 'dsip';
UPDATE compounds SET half_life = '~10-15 minutes' WHERE slug = 'epithalon';
UPDATE compounds SET half_life = '~2 hours' WHERE slug = 'follistatin';
UPDATE compounds SET half_life = '~24-36 hours' WHERE slug = 'foxo4-dri';
UPDATE compounds SET half_life = '~5-10 minutes' WHERE slug = 'ghk-cu';
UPDATE compounds SET half_life = '~30 minutes' WHERE slug = 'ghrp-2';
UPDATE compounds SET half_life = '~2.5 hours' WHERE slug = 'ghrp-6';
UPDATE compounds SET half_life = '~30 hours (TB-500) / ~30 min (BPC-157) / ~5-10 min (GHK-Cu)' WHERE slug = 'glow';
UPDATE compounds SET half_life = '~10-15 minutes' WHERE slug = 'glutathione';
UPDATE compounds SET half_life = '~24-36 hours' WHERE slug = 'hcg';
UPDATE compounds SET half_life = '~55 minutes' WHERE slug = 'hexarelin';
UPDATE compounds SET half_life = '~3 minutes' WHERE slug = 'hgh-fragment-176-191';
UPDATE compounds SET half_life = '~11-23 hours' WHERE slug = 'hmg';
UPDATE compounds SET half_life = '~2 hours' WHERE slug = 'ipamorelin';
UPDATE compounds SET half_life = '~4 minutes' WHERE slug = 'kisspeptin-10';
UPDATE compounds SET half_life = '~30 hours (TB-500) / ~30 min (BPC-157) / ~5-10 min (GHK-Cu) / ~1.5 hours (KPV)' WHERE slug = 'klow';
UPDATE compounds SET half_life = '~1.5 hours' WHERE slug = 'kpv';
UPDATE compounds SET half_life = '~15 hours' WHERE slug = 'l-carnitine';
UPDATE compounds SET half_life = '~1-2 hours (Riboflavin) / ~6-9 hours (Bromelain)' WHERE slug = 'lemon-bottle';
UPDATE compounds SET half_life = '~5 min (Semax) / ~2 min (Selank)' WHERE slug = 'limitless-stack';
UPDATE compounds SET half_life = '~2-4 hours (Lipotropic blend)' WHERE slug = 'lipo-c';
UPDATE compounds SET half_life = '~30 minutes' WHERE slug = 'll-37';
UPDATE compounds SET half_life = '~30 minutes' WHERE slug = 'mots-c';
UPDATE compounds SET half_life = '~30 minutes' WHERE slug = 'mt-1';
UPDATE compounds SET half_life = '~2-4 hours' WHERE slug = 'nad-plus';
UPDATE compounds SET half_life = '~3-5 minutes' WHERE slug = 'oxytocin';
UPDATE compounds SET half_life = '~5-10 minutes' WHERE slug = 'pinealon';
UPDATE compounds SET half_life = '~2.7 hours' WHERE slug = 'pt-141';
UPDATE compounds SET half_life = '~2 minutes' WHERE slug = 'selank';
UPDATE compounds SET half_life = '~5 minutes' WHERE slug = 'semax';
UPDATE compounds SET half_life = '~5 days (Tirzepatide) / ~3 min (AOD9604)' WHERE slug = 'shred-stack';
UPDATE compounds SET half_life = '~1-2 hours' WHERE slug = 'snap-8';
UPDATE compounds SET half_life = '~4 hours' WHERE slug = 'ss-31';
UPDATE compounds SET half_life = '~30 hours' WHERE slug = 'tb-500';
UPDATE compounds SET half_life = '~26-38 minutes' WHERE slug = 'tesamorelin';
UPDATE compounds SET half_life = '~15 minutes' WHERE slug = 'thymalin';
UPDATE compounds SET half_life = '~2 hours' WHERE slug = 'thymosin-alpha-1';
UPDATE compounds SET half_life = '~1-2 minutes' WHERE slug = 'vip';
