-- TOMBSTONE — superseded by 20260605070000_auto_admin_conversation.sql
--
-- This file previously contained the fix-45 auto_admin_conversation SQL,
-- but its version prefix (20260601000001) collided with
-- 20260601000001_shippo_platform.sql, which the Supabase CLI does not allow.
-- The full SQL now lives at 20260605070000_auto_admin_conversation.sql.
--
-- This file SHOULD be deleted from the repo — it's left as a tombstone
-- because the agent that pushed the rename did not have a GitHub MCP
-- delete operation available. To finish the cleanup:
--
--   git rm supabase/migrations/20260601000001_auto_admin_conversation.sql
--   git commit -m 'cleanup: remove tombstoned migration file'
--
-- Production DB is unaffected either way (the functions + trigger have been
-- live since the original apply on 2026-06-01; the rebased migration is
-- idempotent CREATE OR REPLACE).
