-- MOVED on 2026-05-29: this migration's content was relocated to a uniquely
-- versioned timestamp to resolve the on-disk filename collision with the
-- recommendations migration that also bore version 20260530500000.
--
-- The disclaimer order-id FK, supporting index, and order_items_quantity_cap
-- CHECK now live in 20260529230000_hotfix_drop_double_inventory_trigger_and_disclaimer_order_fk.sql
-- and were applied to ydsaqnnuwyvtyxgvrnys via the Supabase MCP on 2026-05-29.
--
-- This stub remains as a no-op so the timestamp is preserved in history
-- without re-running the DDL.
SELECT 1;
